import type { PanelDefinition, PanelGroup, PanelTypeId } from "./types";
import { RV_REGISTRY } from "../rv-registry";

export const PANEL_LIBRARY: Record<PanelTypeId, PanelDefinition> = {
  "six-up-viewer": {
    id: "six-up-viewer",
    title: "6-Up Viewer",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "Review six connected Retroverse public experiences using one canonical song.",
    primaryAction: { label: "Open 6-Up Viewer", href: "/review/public-v3" },
  },
  "current-event": {
    id: "current-event",
    title: "Current Event",
    group: "build",
    defaultStatus: "nominal",
    summary: "Active production event and shared context.",
    primaryAction: { label: "Event Hub", href: "/bobos/event" },
    secondaryActions: [
      { label: "Producer", href: "/bobos/producer" },
      { label: "Docs", href: "/bobos/docs/RV02-01" },
    ],
  },
  "todays-tasks": {
    id: "todays-tasks",
    title: "Today's Tasks",
    group: "attention",
    defaultStatus: "warning",
    summary: "Priority checklist for today's session.",
    primaryAction: { label: "View Tasks", href: "/bobos/event" },
  },
  "current-sprint": {
    id: "current-sprint",
    title: "Current Sprint",
    group: "attention",
    defaultStatus: "nominal",
    summary: "Active sprint scope and milestone status.",
    primaryAction: null,
  },
  alerts: {
    id: "alerts",
    title: "Alerts",
    group: "attention",
    defaultStatus: "alert",
    summary: "System and production alerts requiring attention.",
    primaryAction: null,
  },
  "next-action": {
    id: "next-action",
    title: "Next Action",
    group: "attention",
    defaultStatus: "warning",
    summary: "Recommended next step in the workflow.",
    primaryAction: null,
  },
  credentials: {
    id: "credentials",
    title: "Credentials",
    description: "AI Credential Studio",
    group: "build",
    defaultStatus: "nominal",
    summary: "AI Credential Studio",
    primaryAction: { label: "Open Credentials", href: "/bobos/credentials" },
  },
  "pass-production": {
    id: "pass-production",
    title: "Pass Production",
    group: "build",
    defaultStatus: "nominal",
    summary: "Pass artwork, preview, and print sheet production.",
    primaryAction: { label: "Open Passes", href: "/bobos/passes" },
    secondaryActions: [{ label: "Docs", href: "/bobos/docs/RV02-03" }],
  },
  "event-producer": {
    id: "event-producer",
    title: "Event Producer",
    group: "build",
    defaultStatus: "nominal",
    summary: "Event production plan — passes, giveaway, and homepage flow.",
    primaryAction: { label: "Open Producer", href: "/bobos/producer" },
    secondaryActions: [
      { label: "Event Hub", href: "/bobos/event" },
      { label: "Docs", href: "/bobos/docs/RV02-02" },
    ],
  },
  "event-studio": {
    id: "event-studio",
    title: "Event Production",
    group: "build",
    defaultStatus: "nominal",
    summary: "Producer plan, giveaway, and homepage flow.",
    primaryAction: { label: "Producer", href: "/bobos/producer" },
    secondaryActions: [{ label: "Homepage", href: "/ops/event-studio/homepage" }],
  },
  "poster-builder": {
    id: "poster-builder",
    title: "Poster Builder",
    group: "build",
    defaultStatus: "offline",
    summary: "Poster design workspace (placeholder).",
    primaryAction: null,
  },
  "print-queue": {
    id: "print-queue",
    title: "Print Queue",
    group: "build",
    defaultStatus: "nominal",
    summary: "Pending print jobs and sheet status.",
    primaryAction: { label: "Design Builder", href: "/bobos/passes" },
  },
  "documentary-progress": {
    id: "documentary-progress",
    title: "Documentary Progress",
    group: "build",
    defaultStatus: "warning",
    summary: "Documentary production milestones.",
    primaryAction: null,
  },
  "production-queue": {
    id: "production-queue",
    title: "Production Queue",
    group: "build",
    defaultStatus: "nominal",
    summary: "Queued production jobs across departments.",
    primaryAction: { label: "Ops Center", href: "/ops" },
  },
  "current-song": {
    id: "current-song",
    title: "Current Song",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "Active RVTR track identity and package.",
    primaryAction: { label: "Intelligence", href: "/ops/intelligence" },
  },
  "experience-inspector": {
    id: "experience-inspector",
    title: "Song Workspace",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "The complete Retroverse workspace for one song — public preview, health, and next actions.",
    primaryAction: { label: "Open Song Workspace", href: "/bobos/song-workspace" },
  },
  "song-packages": {
    id: "song-packages",
    title: "Song Packages",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "Song package workbench and completion status.",
    primaryAction: { label: "Packages", href: "/ops/intelligence" },
  },
  "artist-package": {
    id: "artist-package",
    title: "Artist Package",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "Artist-level package and graph context.",
    primaryAction: { label: "Pipeline", href: "/bobos/pipeline" },
  },
  "media-library": {
    id: "media-library",
    title: "Media Library",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "Local media assets and content library.",
    primaryAction: { label: "Content Creator", href: "/ops/content-creator" },
  },
  collectibles: {
    id: "collectibles",
    title: "Collectibles",
    group: "catalog",
    defaultStatus: "offline",
    summary: "Collectible catalog workspace (placeholder).",
    primaryAction: null,
  },
  years: {
    id: "years",
    title: "Years",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "Year-based catalog navigation.",
    primaryAction: { label: "Years Ops", href: "/ops" },
  },
  "virtualdj-status": {
    id: "virtualdj-status",
    title: "VirtualDJ Status",
    group: "devices",
    defaultStatus: "nominal",
    summary: "VirtualDJ bridge and deck connection.",
    primaryAction: { label: "Browser+", href: "/ops/browser-plus" },
    secondaryActions: [{ label: "Bridge", href: "/bobos/bridge" }],
  },
  "ai-queue": {
    id: "ai-queue",
    title: "AI Queue",
    group: "devices",
    defaultStatus: "warning",
    summary: "Pending AI jobs and usage tracking.",
    primaryAction: { label: "AI Workbench", href: "/ops/intelligence" },
    secondaryActions: [{ label: "AI Usage", href: "/bobos/ai" }],
  },
  terminal: {
    id: "terminal",
    title: "Terminal",
    group: "devices",
    defaultStatus: "offline",
    summary: "Command terminal (placeholder v1).",
    primaryAction: { label: "Scripts", href: "/ops/atlas/scripts" },
  },
  "git-status": {
    id: "git-status",
    title: "Git Status",
    group: "devices",
    defaultStatus: "nominal",
    summary: "Repository branch and working tree summary.",
    primaryAction: null,
  },
  "system-health": {
    id: "system-health",
    title: "System Health",
    group: "devices",
    defaultStatus: "nominal",
    summary: "Local services and ops gate status.",
    primaryAction: { label: "Ops", href: "/ops" },
  },
  storage: {
    id: "storage",
    title: "Storage",
    group: "devices",
    defaultStatus: "nominal",
    summary: "RETROVERSE_DATA disk and cache usage.",
    primaryAction: null,
  },
  "database-health": {
    id: "database-health",
    title: "Database Health",
    group: "devices",
    defaultStatus: "nominal",
    summary: "Graph index and data store connectivity.",
    primaryAction: null,
  },
  "catalog-integrity": {
    id: "catalog-integrity",
    title: "Catalog Integrity",
    group: "catalog",
    defaultStatus: "warning",
    summary: "Catalog identity health and open integrity issues.",
    primaryAction: { label: "Open Integrity Dashboard", href: "/ops/integrity" },
  },
  clock: {
    id: "clock",
    title: "Clock",
    group: "devices",
    defaultStatus: "nominal",
    summary: "Local mission time.",
    primaryAction: null,
  },
  notes: {
    id: "notes",
    title: "Notes",
    group: "devices",
    defaultStatus: "offline",
    summary: "Quick mission notes (placeholder v1).",
    primaryAction: null,
  },
  "printer-panel": {
    id: "printer-panel",
    title: "Printer Panel",
    group: "devices",
    defaultStatus: "warning",
    summary: "Print device status and queue.",
    primaryAction: { label: "Design Builder", href: "/bobos/passes" },
  },
  "public-homepage": {
    id: "public-homepage",
    title: "Public Homepage",
    group: "build",
    defaultStatus: "nominal",
    summary: "Public homepage status and active event.",
    primaryAction: { label: "Open Public Homepage", href: "http://localhost:3100/" },
    secondaryActions: [
      { label: "Homepage Preview", href: "/ops/event-studio/homepage" },
      { label: "Set Active Event", href: "/ops/event-control" },
    ],
  },
  "pass-management": {
    id: "pass-management",
    title: "Pass Management",
    group: "build",
    defaultStatus: "nominal",
    summary: "Manage claimed/unclaimed passes from the public claim system.",
    primaryAction: { label: "Open Pass Management", href: "/bobos/pass-management" },
    secondaryActions: [
      { label: "Design Builder", href: "/bobos/passes" },
      { label: "Docs", href: "/bobos/docs/RV02-05" },
    ],
  },
  "giveaway-panel": {
    id: "giveaway-panel",
    title: "Giveaway",
    group: "build",
    defaultStatus: "nominal",
    summary: "Prize drawing state and eligible entries.",
    primaryAction: { label: "Open Giveaway Admin", href: "/ops/event-studio/giveaway" },
    secondaryActions: [
      { label: "Pick Winner", href: "/ops/event-studio/giveaway/drawing" },
      { label: "Display Winner", href: "/ops/event-studio/giveaway/history" },
    ],
  },
  "live-display": {
    id: "live-display",
    title: "Live Display",
    group: "devices",
    defaultStatus: "nominal",
    summary: "What the public display is showing now.",
    primaryAction: { label: "Open Live Display", href: "/sunday-nights" },
    secondaryActions: [
      { label: "Open Live Control", href: "/ops/live-control" },
      { label: "Open VirtualDJ Bridge", href: "/bobos/bridge" },
    ],
  },
  broadcast: {
    id: "broadcast",
    title: "Broadcast Mixer",
    group: "devices",
    defaultStatus: "nominal",
    summary: "Select which of four inputs feeds retroverse.live.",
    primaryAction: { label: "Open Broadcast Mixer", href: "/bobos/broadcast" },
    secondaryActions: [
      { label: "Open Local", href: "http://localhost:3100/" },
      { label: "Open Public", href: "https://retroverse.live/" },
    ],
  },
  "retroverse-runtime": {
    id: "retroverse-runtime",
    title: "Runtime",
    group: "devices",
    defaultStatus: "nominal",
    summary: "Start, stop, and monitor Studio and Live dev servers.",
    primaryAction: { label: "Open Runtime", href: "/bobos/runtime" },
    secondaryActions: [{ label: "Open Live", href: "http://localhost:3100/" }],
  },
  "song-requests": {
    id: "song-requests",
    title: "Song Requests",
    group: "devices",
    defaultStatus: "offline",
    summary: "Review and manage live audience requests",
    primaryAction: { label: "Open Song Requests", href: "http://localhost:3000/bobos/song-requests" },
  },
  "graph-bridge": {
    id: "graph-bridge",
    title: "Album Link Panel",
    group: "catalog",
    defaultStatus: "nominal",
    summary: "Read-only song-to-album relationship surface.",
    primaryAction: { label: "Open Album Link Panel", href: "/ops/graph-bridge" },
  },
};

export const PANEL_LIBRARY_GROUPS: PanelGroup[] = ["attention", "build", "catalog", "devices"];

export function panelsInGroup(group: PanelGroup): PanelDefinition[] {
  const registeredPanelTypes = new Set(RV_REGISTRY.filter((entry) => entry.panelEligible && entry.panelType).map((entry) => entry.panelType));
  return Object.values(PANEL_LIBRARY).filter((panel) => panel.group === group && registeredPanelTypes.has(panel.id));
}

export function getPanelDefinition(id: PanelTypeId): PanelDefinition {
  return PANEL_LIBRARY[id];
}

/** Bottom command bar — quick navigation outside the grid. */
export const COCKPIT_COMMAND_BAR = [
  { label: "Documentation", href: "/bobos/docs" },
  { label: "RV Directory", href: "/bobos/rv-directory" },
  { label: "Broadcast Mixer", href: "/bobos/broadcast" },
  { label: "Credentials", href: "/bobos/credentials" },
  { label: "Event Producer", href: "/bobos/producer" },
  { label: "Design Builder", href: "/bobos/passes" },
  { label: "Posters", href: "/bobos/event" },
  { label: "Website", href: "/ops/event-studio/homepage" },
  { label: "Documentary", href: "/ops" },
  { label: "AI Workbench", href: "/ops/intelligence" },
  { label: "Terminal", href: "/ops/atlas/scripts" },
  { label: "VirtualDJ", href: "/ops/browser-plus" },
  { label: "Song Requests", href: "http://localhost:3000/bobos/song-requests", panelType: "song-requests" },
  { label: "Printer", href: "/bobos/passes" },
] as const;
