import type { SearchPanels } from "./types";

/**
 * MOCK DATA — discovery panels only.
 *
 * Future DB wiring: replace with `searchRetroverse(query)` returning
 * `{ albums, songs, artistsCharts }` from your index/API.
 */
export const MOCK_SEARCH_PANELS: SearchPanels = {
  albums: [
    {
      id: "album-thriller",
      title: "Thriller",
      artist: "Michael Jackson",
      year: 1982,
      chartNote: "#1 Billboard 200 · 37 weeks",
      hasVdj: true,
      coverAccent: "#e85d1a",
      coverUrl:
        "https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png",
    },
    {
      id: "album-purple-rain",
      title: "Purple Rain",
      artist: "Prince",
      year: 1984,
      chartNote: "Soundtrack · 13M+ US",
      hasVdj: true,
      coverAccent: "#7b3fa8",
    },
    {
      id: "album-rumours",
      title: "Rumours",
      artist: "Fleetwood Mac",
      year: 1977,
      chartNote: "40+ weeks #1 UK",
      coverAccent: "#2a5f9e",
      coverUrl:
        "https://upload.wikimedia.org/wikipedia/en/f/fb/FmacRumours.PNG",
    },
    {
      id: "album-escape",
      title: "Escape",
      artist: "Journey",
      year: 1981,
      chartNote: "Diamond · US",
      coverAccent: "#1f7a4a",
    },
    {
      id: "album-appetite",
      title: "Appetite for Destruction",
      artist: "Guns N' Roses",
      year: 1987,
      chartNote: "18M+ US",
      hasVdj: true,
      coverAccent: "#b83d2a",
    },
    {
      id: "album-hotel-california",
      title: "Hotel California",
      artist: "Eagles",
      year: 1976,
      chartNote: "#1 Billboard 200",
      hasVdj: true,
      coverAccent: "#c9a020",
    },
  ],
  songs: [
    {
      id: "song-billie-jean",
      title: "Billie Jean",
      artist: "Michael Jackson",
      year: 1983,
      chartNote: "#1 Hot 100 · 7 weeks",
      hasVdj: true,
      coverAccent: "#0d6e7a",
    },
    {
      id: "song-purple-rain",
      title: "Purple Rain",
      artist: "Prince",
      year: 1984,
      chartNote: "#2 Hot 100",
      hasVdj: true,
      coverAccent: "#5c3d9e",
    },
    {
      id: "song-dont-stop",
      title: "Don't Stop Believin'",
      artist: "Journey",
      year: 1981,
      chartNote: "#9 Hot 100",
      hasVdj: true,
      coverAccent: "#1a6b6b",
    },
    {
      id: "song-dreams",
      title: "Dreams",
      artist: "Fleetwood Mac",
      year: 1977,
      chartNote: "#1 Hot 100",
      hasVdj: true,
      coverAccent: "#2a5f9e",
    },
    {
      id: "song-sweet-child",
      title: "Sweet Child O' Mine",
      artist: "Guns N' Roses",
      year: 1988,
      chartNote: "#1 Hot 100",
      coverAccent: "#b83d2a",
    },
    {
      id: "song-like-a-virgin",
      title: "Like a Virgin",
      artist: "Madonna",
      year: 1984,
      chartNote: "#1 Hot 100 · 6 weeks",
      hasVdj: true,
      coverAccent: "#e85d1a",
    },
    {
      id: "song-beat-it",
      title: "Beat It",
      artist: "Michael Jackson",
      year: 1983,
      chartNote: "#1 Hot 100",
      hasVdj: true,
      coverAccent: "#12343a",
    },
    {
      id: "song-hotel-california",
      title: "Hotel California",
      artist: "Eagles",
      year: 1977,
      chartNote: "#1 Hot 100",
      hasVdj: true,
      coverAccent: "#c96a30",
    },
  ],
  artistsCharts: [
    {
      id: "artist-mj",
      title: "Michael Jackson",
      subtitle: "Artist",
      year: 1982,
      chartNote: "King of Pop era",
      kind: "artist",
      coverAccent: "#e85d1a",
    },
    {
      id: "artist-prince",
      title: "Prince",
      subtitle: "Artist",
      year: 1984,
      chartNote: "Minneapolis sound",
      kind: "artist",
      coverAccent: "#7b3fa8",
    },
    {
      id: "chart-1984-hot100",
      title: "1984",
      subtitle: "Hot 100 Year",
      year: 1984,
      chartNote: "Billboard chart year",
      kind: "chart",
      coverAccent: "#0d6e7a",
    },
    {
      id: "artist-fleetwood",
      title: "Fleetwood Mac",
      subtitle: "Artist",
      year: 1977,
      chartNote: "Rumours era",
      kind: "artist",
      hasVdj: true,
      coverAccent: "#2a5f9e",
    },
    {
      id: "chart-1977-hot100",
      title: "1977",
      subtitle: "Hot 100 Year",
      year: 1977,
      chartNote: "Billboard chart year",
      kind: "chart",
      coverAccent: "#1f7a4a",
    },
    {
      id: "artist-madonna",
      title: "Madonna",
      subtitle: "Artist",
      year: 1984,
      chartNote: "Like a Virgin breakout",
      kind: "artist",
      coverAccent: "#ffb5a7",
    },
    {
      id: "artist-beatles",
      title: "The Beatles",
      subtitle: "Artist",
      year: 1969,
      chartNote: "Abbey Road era",
      kind: "artist",
      coverAccent: "#5c3d9e",
    },
    {
      id: "chart-1983-hot100",
      title: "1983",
      subtitle: "Hot 100 Year",
      year: 1983,
      chartNote: "Thriller dominates",
      kind: "chart",
      coverAccent: "#c9a020",
    },
  ],
};
