import type { VdjPoolSong } from "./types";
import { buildAssociationVector, type AssociationSpace } from "./cultural-association-core";

/** Internal 1978 DJ-association spaces — never shown as genre labels. */
export const ASSOCIATION_SPACES_1978: AssociationSpace[] = [
  {
    id: "disco_dancefloor",
    artists: [
      "bee gees",
      "chic",
      "village people",
      "boney m",
      "earth wind",
      "donna summer",
      "gloria gaynor",
      "kool",
      "gang",
      "sylvester",
      "heatwave",
      "tavares",
    ],
    titles: [
      "le freak",
      "ymca",
      "tragedy",
      "stayin alive",
      "night fever",
      "miss you",
      "september",
      "rivers of babylon",
      "grease",
      "you are the one",
      "hot child",
      "born to hand jive",
    ],
  },
  {
    id: "soft_yacht_rock",
    artists: [
      "billy joel",
      "barry manilow",
      "andrew gold",
      "walter egan",
      "gerry rafferty",
      "nicole larson",
      "little river band",
      "kenny rogers",
      "reo speedwagon",
      "bob seger",
      "meat loaf",
      "eddie money",
      "burton cummings",
    ],
    titles: [
      "baker street",
      "magnet and steel",
      "thank you for being",
      "still the same",
      "baby hold on",
      "time for me to fly",
      "the gambler",
      "lotta love",
      "two out of three",
      "copacabana",
      "only the good die young",
      "break it to them",
    ],
  },
  {
    id: "arena_classic_rock",
    artists: [
      "cheap trick",
      "van halen",
      "kiss",
      "queen",
      "rolling stones",
      "bob seger",
      "styx",
      "electric light",
      "elo",
      "dire straits",
      "joe walsh",
      "trooper",
      "three dog night",
    ],
    titles: [
      "surrender",
      "runnin with the devil",
      "rock and roll all night",
      "baba o",
      "sultans of swing",
      "sweet talkin woman",
      "fooling yourself",
      "shambala",
      "raise a little hell",
      "life's been good",
      "bicycle race",
    ],
  },
  {
    id: "new_wave_punk",
    artists: [
      "blondie",
      "talking heads",
      "devo",
      "ramones",
      "the cars",
      "nick gilder",
      "cheap trick",
    ],
    titles: [
      "heart of glass",
      "just what i needed",
      "i wanna be sedated",
      "satisfaction",
      "take me to the river",
      "hot child in the city",
    ],
  },
  {
    id: "country_crossover",
    artists: [
      "willie nelson",
      "kenny rogers",
      "olivia newton",
      "exile",
      "suzi quatro",
    ],
    titles: [
      "mammas don't let",
      "the gambler",
      "kiss you all over",
      "stumblin",
      "lady 1978",
    ],
  },
  {
    id: "pop_abba_radio",
    artists: ["abba", "10cc", "frankie valli", "linda ronstadt", "exile"],
    titles: [
      "take a chance",
      "dreadlock holiday",
      "just one look",
      "lady 1978",
      "kiss you all over",
    ],
  },
  {
    id: "novelty_tv_comedy",
    artists: ["steve martin", "warren zevon", "sha na na", "frankie valli"],
    titles: ["king tut", "werewolves of london", "born to hand jive", "grease"],
  },
  {
    id: "beatles_legacy",
    artists: ["beatles", "the who"],
    titles: ["a day in the life", "baba o"],
  },
];

export function associationVector1978(song: VdjPoolSong): number[] {
  return buildAssociationVector(song, ASSOCIATION_SPACES_1978);
}
