import type { VdjPoolSong } from "./types";
import { buildAssociationVector, type AssociationSpace } from "./cultural-association-core";

/** Internal 1992 DJ-association spaces — never shown as genre labels. */
export const ASSOCIATION_SPACES_1992: AssociationSpace[] = [
  {
    id: "grunge_alt_rock",
    artists: [
      "nirvana",
      "pearl jam",
      "soundgarden",
      "alice in chains",
      "stone temple",
      "radiohead",
      "rem",
      "red hot",
      "ugly kid",
      "spin doctors",
      "cranberries",
      "cure",
    ],
    titles: [
      "lithium",
      "creep",
      "man on the moon",
      "give it away",
      "down in a hole",
      "everything about you",
      "little miss",
      "dreams",
      "friday i'm in love",
    ],
  },
  {
    id: "hip_hop_rnb",
    artists: [
      "sir mix",
      "house of pain",
      "naughty by nature",
      "arrested development",
      "wreckx",
      "n2deep",
      "paperboy",
      "tony",
      "bobby brown",
      "mary j blige",
      "snow",
      "kris kross",
      "us3",
    ],
    titles: [
      "baby got back",
      "jump around",
      "hip hop hooray",
      "tennessee",
      "rump shaker",
      "back to the hotel",
      "ditty",
      "feels good",
      "humpin",
      "real love",
      "informer",
      "jump",
      "cantaloop",
    ],
  },
  {
    id: "dance_electronic",
    artists: [
      "snap",
      "c+c music",
      "2 unlimited",
      "captain hollywood",
      "bizarre inc",
      "k.w.s",
      "robin s",
      "madonna",
      "prince",
    ],
    titles: [
      "rhythm is a dancer",
      "gonna make you sweat",
      "twilight zone",
      "more more",
      "i'm gonna get you",
      "please don't go",
      "show me love",
      "erotica",
      "7",
    ],
  },
  {
    id: "country_boom",
    artists: [
      "billy ray cyrus",
      "alan jackson",
      "confederate railroad",
      "john anderson",
      "garth",
    ],
    titles: [
      "achy breaky",
      "chattahoochee",
      "trashy women",
      "seminole wind",
    ],
  },
  {
    id: "power_ballad_rock",
    artists: [
      "guns n",
      "bon jovi",
      "meat loaf",
      "eric clapton",
      "van halen",
      "neil young",
      "sophie b",
    ],
    titles: [
      "november rain",
      "bed of roses",
      "i'd do anything",
      "tears in heaven",
      "right now",
      "harvest moon",
      "damn i wish",
    ],
  },
  {
    id: "pop_radio",
    artists: [
      "en vogue",
      "annie lennox",
      "jon secada",
      "michael jackson",
      "madonna",
      "cher",
    ],
    titles: [
      "free your mind",
      "walking on broken glass",
      "just another day",
      "remember the time",
      "erotica",
      "i got you babe",
    ],
  },
  {
    id: "early_90s_novelty",
    artists: ["cher", "snow", "ugly kid", "sir mix"],
    titles: ["i got you babe", "informer", "everything about you", "baby got back"],
  },
];

export function associationVector1992(song: VdjPoolSong): number[] {
  return buildAssociationVector(song, ASSOCIATION_SPACES_1992);
}
