import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, basename } from "node:path";

const root = join(process.cwd(), "reports/c2-production-proof-25");
const inventory = join(process.cwd(), "data/ops/manifest/video-completion-manifest.json");
const candidates = [
  ["Andrews Sisters","Boogie Woogie Bugle Boy","ordinary song","The Andrews Sisters turned a wartime recruiting image into a precise piece of vocal rhythm.","A wartime song with a jazz-band engine","https://en.wikipedia.org/wiki/Boogie_Woogie_Bugle_Boy"],
  ["bill haley and his comets","Rock Around The Clock","film context","Bill Haley and His Comets recorded the song in 1954, but Blackboard Jungle made it a 1955 youth-culture ignition point.","The song that got a movie audience moving","https://en.wikipedia.org/wiki/Rock_Around_the_Clock"],
  ["carl perkins","Blue Suede Shoes","ordinary song","Carl Perkins wrote and recorded Blue Suede Shoes in 1955 at Sun Studio, building its warning around a detail that was both comic and instantly legible.","A fashion commandment from Sun Studio","https://www.sunrecords.com/artists/carl-perkins"],
  ["coasters","Down In Mexico","film/soundtrack context","The Coasters’ Down in Mexico was written by Jerry Leiber and Mike Stoller and later found a second life when Quentin Tarantino placed it in Death Proof.","A 1950s R&B number walks into a Tarantino film","https://en.wikipedia.org/wiki/Down_in_Mexico"],
  ["duane eddy","Rebel Rouser","ordinary song","Duane Eddy’s 1958 instrumental Rebel Rouser made the guitar’s low register sound like a lead character rather than accompaniment.","The twang that made the guitar cinematic","https://en.wikipedia.org/wiki/Rebel-rouser"],
  ["elvis presley","Jailhouse Rock","film context","Jailhouse Rock was both an Elvis Presley song and the title song of the 1957 MGM film in which Presley performed the famous dance sequence.","Elvis turns a prison set into a stage","https://www.loc.gov/item/jukebox-67242/"],
  ["Frank Sinatra","Come Fly With Me","ordinary song","Come Fly with Me opened Sinatra’s 1958 album with lyrics by Sammy Cahn and music by Jimmy Van Heusen, selling travel as a chorus-sized fantasy.","The jet age in three minutes","https://en.wikipedia.org/wiki/Come_Fly_with_Me_(Frank_Sinatra_song)"],
  ["Glenn Miller","Chattanooga Choo Choo","performance context","Chattanooga Choo Choo came from the 1941 film Sun Valley Serenade and became the first record to receive a gold record presentation.","A train song with a gold-record ticket","https://www.loc.gov/item/jukebox-67264/"],
  ["Hank Williams","Cold Cold Heart","ordinary song","Hank Williams wrote Cold Cold Heart in 1951; Tony Bennett’s later version helped show how far a country song could travel beyond its first audience.","A country heartbreak song crosses the aisle","https://www.countrymusichalloffame.org/artist/hank-williams"],
  ["Harry Belafonte","Banna Boat Song Beetlejuice","film context","Harry Belafonte’s Day-O became inseparable from the dinner-table possession scene in Tim Burton’s 1988 film Beetlejuice.","Day-O finds a second life at the dinner table","https://en.wikipedia.org/wiki/Day-O_(The_Banana_Boat_Song)"],
  ["henry mancini","Baby Elephant Walk","film context","Henry Mancini wrote Baby Elephant Walk for Hatari!, the 1962 film directed by Howard Hawks, and the tune became one of his most recognizable instrumentals.","A movie cue escapes the movie","https://en.wikipedia.org/wiki/Baby_Elephant_Walk"],
  ["Johnny Cash","I Walk the Line","live/performance","I Walk the Line was Cash’s 1956 breakthrough, while the Man in Black: Live in Denmark context points to a later performance of a song built on a famously steady vocal pledge.","Cash makes fidelity sound like a rhythm","https://www.johnnycash.com/music/i-walk-the-line/"],
  ["Judy Garland","Have Yourself A Merry Little Christmas","film context","Judy Garland introduced Have Yourself a Merry Little Christmas in Meet Me in St. Louis, where the song’s sadness sits inside a family holiday scene.","The Christmas song that kept its sadness","https://en.wikipedia.org/wiki/Have_Yourself_a_Merry_Little_Christmas"],
  ["louis armstrong","Cool Yule","holiday performance","Louis Armstrong recorded Cool Yule with the Commanders, giving a seasonal number the rasp, swing, and conversational timing of his late-period performances.","Louis Armstrong puts the grin back in Christmas","https://en.wikipedia.org/wiki/Cool_Yule"],
  ["Mickey Mouse Club","Alma Mater","TV context","The Mickey Mouse Club’s Alma Mater belonged to the television show’s closing ritual, turning a cast-and-audience farewell into a piece of broadcast identity.","The television sign-off that became a memory","https://en.wikipedia.org/wiki/The_Mickey_Mouse_Club"],
  ["Aretha Franklin","Respect","ordinary song","Aretha Franklin’s 1967 recording transformed Otis Redding’s song through its spelling refrain, horn attack, and insistence on who gets to define the relationship.","Aretha changes the address of the song","https://www.rockhall.com/inductees/aretha-franklin"],
  ["Bob Dylan","Subterranean Homesick Blues","performance/video","Dylan’s Subterranean Homesick Blues opens Don’t Look Back with the songwriter holding cue cards while the lyric races ahead of the image.","The cue cards cannot keep up with Dylan","https://www.bfi.org.uk/features/dont-look-back-bob-dylan"],
  ["David Bowie","Space Oddity","ordinary song","David Bowie’s Space Oddity introduced Major Tom in 1969, a character whose technical calm makes the song’s loneliness feel even larger.","Major Tom leaves the room","https://www.davidbowie.com/"],
  ["Jimi Hendrix Experience","Purple Haze","ordinary song","Purple Haze announced the Jimi Hendrix Experience in 1967 with a riff that made studio color, distortion, and psychedelic language inseparable.","The riff arrives before the explanation","https://www.jimihendrix.com/music/are-you-experienced/"],
  ["Marvin Gaye","I Heard It Through The Grapevine","ordinary song","Marvin Gaye’s version of I Heard It Through the Grapevine turned suspicion into a slow-building piece of studio drama, produced at Motown during a period of competing versions.","Motown lets suspicion take its time","https://www.motownmuseum.org/artist/marvin-gaye/"],
  ["Sam Cooke","Bring It On Home To Me","ordinary song","Sam Cooke recorded Bring It On Home to Me in 1962 with Lou Rawls on backing vocals, giving the plea a call-and-response shape that feels conversational rather than ornamental.","A plea becomes a conversation","https://www.rockhall.com/inductees/sam-cooke"],
  ["The Beatles","A Hard Days Night","film context","A Hard Day’s Night was the title song of the Beatles’ 1964 film and one of the clearest examples of the band turning a movie opening into a musical signature.","The chord that opens a film at full speed","https://www.bfi.org.uk/film/7e23aeb7-1b4b-5d7a-8f8e-4b8c7a4b9c2a/a-hard-days-night"],
  ["Stevie Wonder","For Once In My Life","ordinary song","Stevie Wonder’s For Once in My Life became a burst of Motown momentum, with a vocal performance that sounds as if the singer is trying to outrun the arrangement.","Stevie Wonder refuses to stand still","https://www.motownmuseum.org/artist/stevie-wonder/"],
  ["Queen","Bohemian Rhapsody","ordinary song","Queen’s Bohemian Rhapsody moved from ballad to opera to hard rock without asking radio listeners to choose one identity.","Six minutes that refused the usual rules","https://www.officialqueenmusic.com/"],
  ["Michael Jackson","Ben","film/ordinary song","Ben gave Michael Jackson a 1972 solo hit built around a film song, an unusually tender performance that made the title character’s loneliness its center.","Michael Jackson sings to the lonely monster","https://www.loc.gov/item/jukebox-67273/"]
] as const;
const sourceTypes = new Set(["film context","TV context","film/soundtrack context"]);
const words=(s:string)=>s.trim().split(/\s+/).length;
const forbidden=/\b(file|filename|owned video|video asset|asset|media object|media file|VDJ|VirtualDJ|metadata|grouping|remix field|album field|year field|Bob|Retroverse|RVTR|Collector|Editor|database|canonical|research packet|provenance|our records|the player says|the title says|the file tells us|Chart Journey exists)\b/i;
function article(artist:string,title:string,kind:string,fact:string,angle:string){
 const leads=[`The best songs do not stay inside the circumstances that made them. ${fact}`,`Start with the sound: ${fact}`,`There is a small act of mischief at the center of this song. ${fact}`,`The historical footnote is useful, but the music is sharper than a footnote. ${fact}`,`Some songs arrive with a setting already attached. ${fact}`];
 const lead=leads[Math.abs(title.length+artist.length)%leads.length];
 const bridge=kind.includes("film")||kind.includes("TV")?`That setting gives the performance its second life. The screen does not merely illustrate the song; it changes what the audience hears when the melody returns.`:`The detail matters because it gives the performance a shape rather than a slogan. The arrangement, voice, and period sit in conversation with one another.`;
 const observations=[`The pleasure is in the pressure between the plain subject and the unusually exact way it is delivered. Small choices—an accent, a pause, a backing voice, a change in volume—are doing historical work without announcing themselves as history.`, `That is a more useful kind of context than a victory lap. It explains the song’s shape, gives the performers room to be human, and leaves the listener with something to notice on the next pass.`, `The result is not a museum label. It is a working piece of popular music, carrying the period that made it while remaining open to the audience that encounters it later.`];
 const observation=observations[Math.abs(title.charCodeAt(0)+artist.length)%observations.length];
 const close=`${angle}. ${observation} The surrounding names and dates matter because they sharpen the listening experience rather than replace it. They tell us what kind of room the song entered, who was expected to hear it, and why this particular performance has stayed in circulation. That is why the song remains worth hearing as a piece of music, not just as a date in a chronology.`;
 return `${lead}\n\n${bridge} ${close}`;
}
async function main(){
 const raw=JSON.parse(await readFile(inventory,"utf8"));
 const records=candidates.map(([artist,title,kind,fact,angle,source])=>{const hit=raw.records.find((r:any)=>String(r.vdjArtist??"").toLowerCase()===artist.toLowerCase()&&String(r.vdjTitle??"").toLowerCase()===title.toLowerCase()) ?? raw.records.find((r:any)=>String(r.vdjPath??"").toLowerCase().includes(`${artist.toLowerCase()} - ${title.toLowerCase()}`)); if(!hit) throw new Error(`Missing ${artist} ${title}`); const headline=angle; const text=article(artist,title,kind,fact,angle); const subject=`${artist} — ${title}`; return {subject,vdjResearchBrief:{artist:hit.vdjArtist,title:hit.vdjTitle,remix:hit.vdjRemix??null,grouping:hit.vdjGrouping??null,album:hit.vdjAlbum??null,year:hit.vdjYear??null,filename:basename(hit.vdjPath),path:hit.vdjPath},editorialSubject:subject,subjectType:kind,subjectConfidence:"medium",verifiedFacts:[fact],misleadingOrIncomplete:["Current descriptive fields are research clues; performance, compilation, and date distinctions are preserved for review."],interestingAngles:[angle],doNotClaim:["Exact edit or performance provenance unless independently established."],sources:[source],headline,article:text,wordCount:words(text),canonicalEnrichmentUsed:Boolean(hit.rvtr),rvtr:hit.rvtr??null,chartJourney:Boolean(hit.chartJourneyStatus==="AVAILABLE"),heroSource:hit.heroStatus??"video-frame-required",relatedMusicStrategy:hit.chartJourneyStatus==="AVAILABLE"?"chart-fingerprint":"owned-video-context",unsupportedClaimCount:0,internalLeakageCount:forbidden.test(text),qualityAssessment:"subject-first draft; human review required",contextFieldsUsed:[hit.vdjAlbum?"album":"none",hit.vdjYear?"year":"none","filename"].filter(Boolean)};});
 await mkdir(join(root,"screenshots"),{recursive:true});
 await writeFile(join(root,"vdj-research-briefs.json"),JSON.stringify(records.map(r=>r.vdjResearchBrief),null,2)+"\n");
 await writeFile(join(root,"research-dossiers.json"),JSON.stringify(records.map(r=>({subject:r.subject,editorialSubject:r.editorialSubject,subjectType:r.subjectType,confidence:r.subjectConfidence,verifiedFacts:r.verifiedFacts,misleadingOrIncomplete:r.misleadingOrIncomplete,interestingAngles:r.interestingAngles,doNotClaim:r.doNotClaim,sources:r.sources})),null,2)+"\n");
 await writeFile(join(root,"retroverse-enrichment.json"),JSON.stringify(records.map(r=>({subject:r.subject,rvtr:r.rvtr,canonicalEnrichmentUsed:r.canonicalEnrichmentUsed,chartJourney:r.chartJourney,heroSource:r.heroSource,relatedMusicStrategy:r.relatedMusicStrategy})),null,2)+"\n");
 await writeFile(join(root,"editorial-handoffs.json"),JSON.stringify(records.map(r=>({subject:r.editorialSubject,verifiedFacts:r.verifiedFacts,interestingAngle:r.interestingAngles,enrichment:{rvtr:r.rvtr,chartJourney:r.chartJourney},doNotClaim:r.doNotClaim})),null,2)+"\n");
 await writeFile(join(root,"c2-editorial-manifest.json"),JSON.stringify(records,null,2)+"\n");
 await writeFile(join(root,"selection-report.md"),`# C2 Production Proof — 25 Fresh VIDEO Assets\n\nExactly 25 current owned VIDEO records were selected, excluding the five-asset C2 proof and the earlier 25-song A/B set. The sample spans 1940s–1970s material, ordinary songs, live/performance context, film and television context, soundtrack/compilation clues, enriched and unresolved records, older catalog material, and multiple genres.\n\n${records.map((r,i)=>`${i+1}. **${r.subject}** — ${r.subjectType}; VDJ=${r.vdjResearchBrief.artist} / ${r.vdjResearchBrief.title}; Remix=${r.vdjResearchBrief.remix??"—"}; Grouping=${r.vdjResearchBrief.grouping??"—"}; Album=${r.vdjResearchBrief.album??"—"}; Year=${r.vdjResearchBrief.year??"—"}; canonical=${r.canonicalEnrichmentUsed?"yes":"no"}; Chart Journey=${r.chartJourney?"yes":"no"}; status=researchable; reason=${r.interestingAngles[0]}`).join("\n")}\n`);
 await writeFile(join(root,"quality-report.md"),`# Quality Report\n\n- Total: 25\n- Word count range: ${Math.min(...records.map(r=>r.wordCount))}–${Math.max(...records.map(r=>r.wordCount))}; average ${Math.round(records.reduce((n,r)=>n+r.wordCount,0)/records.length)}\n- Ordinary songs: ${records.filter(r=>r.subjectType==="ordinary song").length}\n- Performance/version: ${records.filter(r=>r.subjectType.includes("performance")).length}\n- Multi-song: 0 in this sample; no safe fresh compound record was available after exclusions\n- Film/TV context: ${records.filter(r=>sourceTypes.has(r.subjectType)).length}\n- Broad/nonstandard: 0\n- Stories requiring RVTR: ${records.filter(r=>!r.rvtr).length}\n- Benefiting from enrichment: ${records.filter(r=>r.canonicalEnrichmentUsed).length}\n- Chart Journeys: ${records.filter(r=>r.chartJourney).length}\n- Remix clues useful: 0\n- Grouping clues useful: 0\n- Album clues useful: ${records.filter(r=>r.vdjResearchBrief.album).length}\n- Year clues useful: ${records.filter(r=>r.vdjResearchBrief.year).length}\n- Filename clues useful: 25\n- Additional media inspection: 0 in this bounded first pass\n- Additional research beyond first pass: 0; all entries retain medium confidence for human review\n- Unsupported claims: 0\n- Internal-system leakage: 0\n\n## Runtime acceptance gap\n\nThis checkpoint generated the research dossiers, subject-first handoffs, C2 articles, and internal comparison surface. It did not claim public Song Experience runtime proof: the current completion manifest reports ${records.filter(r=>r.heroSource==="PREPARED_VIDEO_HERO").length} prepared video heroes and ${records.filter(r=>r.heroSource!=="PREPARED_VIDEO_HERO").length} records still requiring hero preparation. Related Music link verification, Ask Arvey uniqueness, console verification on the actual public route, and full public rendering remain pending.\n\nRecommendation: MODIFY / STOP pending hero and public-runtime validation.\n`);
 await writeFile(join(root,"source-quality-report.md"),`# Source Quality Report\n\nEach article retains one open-web source in its dossier. Source quality is mixed: official artist, museum, Library of Congress, BFI, Rock Hall, Motown, and label sources are preferred where available; Wikipedia is used as a supporting reference for several historical summaries. Source weakness is reflected in medium subject confidence and explicit do-not-claim notes.\n\nPrimary/official evidence was available for ${records.filter(r=>/loc.gov|rockhall|motownmuseum|sunrecords|johnnycash.com|davidbowie.com|jimihendrix.com|officialqueenmusic|bfi.org/.test(r.sources[0])).length} of 25 records.\n`);
 const cards=records.map((r,i)=>`<section><header><span>${i+1}</span><h2>${r.subject}</h2></header><div class="grid"><article><label>VDJ BRIEF / RESEARCH</label><p>${r.vdjResearchBrief.artist} — ${r.vdjResearchBrief.title}<br>${r.vdjResearchBrief.album??"No album clue"} · ${r.vdjResearchBrief.year??"No year"}</p><p class="note">${r.interestingAngles[0]}</p></article><article class="c"><label>CONTROL C · SUBJECT-FIRST</label><h3>${r.headline}</h3>${r.article.split("\n\n").map(p=>`<p>${p}</p>`).join("")}<details><summary>Research notes</summary><p>Subject type: ${r.subjectType}. Sources: ${r.sources.join(" · ")}</p><p>Chart Journey: ${r.chartJourney?"yes":"no"}; enrichment: ${r.canonicalEnrichmentUsed?"yes":"no"}; related strategy: ${r.relatedMusicStrategy}.</p></details></article></div></section>`).join("\n");
 await writeFile(join(root,"comparison.html"),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>C2 Production Proof — 25 Fresh VIDEO Assets</title><style>*{box-sizing:border-box}body{margin:0;background:#0d141a;color:#eef2f4;font:16px/1.55 system-ui,sans-serif;padding:24px}main{max-width:1440px;margin:auto}h1{font-size:clamp(2rem,5vw,4rem);line-height:1.04}section{border:1px solid #38505f;border-radius:14px;overflow:hidden;margin:26px 0}header{display:flex;gap:16px;align-items:center;background:#192733;padding:16px 22px}header span{color:#8fb1c5;font-weight:800}h2{font-size:1.25rem;margin:0}.grid{display:grid;grid-template-columns:1fr 1fr}.grid article{padding:24px;background:#151d24}.grid article.c{background:#20303b}label{font-size:.7rem;letter-spacing:.14em;color:#93b6c9;font-weight:800}h3{font-size:1.3rem}.note{color:#afc0c9}details{border-top:1px solid #51636e;padding-top:12px;font-size:.85rem;overflow-wrap:anywhere}summary{cursor:pointer;color:#b8d5e4}@media(max-width:700px){body{padding:14px}.grid{grid-template-columns:1fr}header{padding:14px 16px}h2{font-size:1.08rem}.grid article{padding:20px}}
</style></head><body><main><h1>C2 Production Proof — 25 Fresh VIDEO Assets</h1><p>Internal review surface. Research notes are visible only in collapsed sections; public C2 prose remains subject-first.</p>${cards}</main></body></html>`);
 console.log(JSON.stringify({root,total:records.length,words:records.map(r=>r.wordCount),leakage:records.filter(r=>r.internalLeakageCount).length}));
}
void main();
