import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = process.cwd();
const MANIFEST = join(ROOT, "data/ops/manifest/video-completion-manifest.json");
const PILOT = join(ROOT, "reports/canonical-optional-completion-50/pilot-manifest.json");
const MEDIA = join(ROOT, "reports/media-aware-identity-50/media-classification-manifest.json");
const OUT = join(ROOT, "reports/editorial-first-completion-50");
const special = new Set(["VERSION_OR_PERFORMANCE", "MULTI_SONG", "NON_SONG_CONTEXT"]);

const proofs: Record<string, any> = {
  "Andrews Sisters - Boogie Woogie Bugle Boy.mp4": { headline: "The Andrews Sisters Put Swing in Uniform", article: "The Andrews Sisters’ close harmonies could sound both precise and exuberant, and “Boogie Woogie Bugle Boy” captures that balance. The song belongs to the trio’s swing-and-boogie-woogie world, where tightly arranged voices supplied their own brass-like energy. A Library of Congress remembrance places the song among the group’s signature repertoire and describes the unusual syncopation and big-band character that kept their performances vivid. The owned video is therefore a strong editorial subject even though its exact recording provenance is not asserted here. The story can stay with the musical fact we can support: three voices, a wartime-era sound, and a performance style built to make ensemble singing feel kinetic.", sources: ["https://blogs.loc.gov/music/2013/02/in-memory-of-patty-andrews-and-the-andrews-sisters/"], hero: "temporary sampled video frames; no durable hero generated" },
  "Cab Calloway - Minnie the Moocher (Blue Brothers).mp4": { headline: "When Cab Calloway Walked Back Into the Spotlight", article: "Cab Calloway’s “Minnie the Moocher” is an ideal editorial subject because the owned video carries two histories at once: the song’s place in Calloway’s repertoire and its later life in The Blues Brothers. Calloway’s official site identifies “Minnie the Moocher” as his signature song and notes the film appearance. The important distinction is performance context: this is a Blues Brothers-era film performance, not evidence that the later clip itself had the historical song’s original chart life. That separation makes the story stronger. It lets the feature move from Calloway’s call-and-response showmanship to the way a movie introduced his persona and song to a new audience without pretending that every date belongs to the same recording.", sources: ["https://www.cabcalloway.com/index.html", "https://en.wikipedia.org/wiki/Cab_Calloway"], hero: "temporary sampled video frames; no durable hero generated" },
  "Buddy Holly - Not Fade Away and Peggy Sue.mp4": { headline: "Two Buddy Holly Songs, One Shared Charge", article: "The owned video names two Buddy Holly songs, so its editorial subject should remain the combined performance rather than choosing a convenient primary title. “Peggy Sue” and “Not Fade Away” belong to the compact, influential body of work that made Holly a foundational rock-and-roll figure. The sources support discussing both songs and Holly’s career, while the media model preserves two underlying relationships for later enrichment. The article can explain the connection naturally: one physical performance, two song identities, and a glimpse of how Holly’s concise melodic language traveled beyond its original moment. Any individual chart journey belongs to the appropriate song relationship, not automatically to the combined video file.", sources: ["https://www.ebsco.com/research-starters/history/buddy-holly", "https://www.theguardian.com/books/2009/feb/08/not-fade-away-buddy-holly"], hero: "temporary sampled video frames; no durable hero generated" },
  "Big Band - Rhapsody in Blue.mp4": { headline: "Rhapsody in Blue Keeps Changing Shape", article: "“Rhapsody in Blue” is a useful editorial subject even when the exact orchestra in an owned video is not established. The Library of Congress describes the work as a landmark in American music and preserves both Gershwin’s manuscript and the history of Ferde Grofé’s orchestrations. That history matters here: the piece was built to move between piano, jazz-band color, and larger performing forces. A generic “Big Band” label is therefore a reason to widen the story, not to invent a performer. The feature can discuss Gershwin’s composition, its orchestral life, and the way arrangements let different ensembles make the same famous musical argument in their own voice.", sources: ["https://www.loc.gov/item/ihas.200156779/", "https://blogs.loc.gov/music/2024/02/rhapsody-in-blue-at-100/"], hero: "temporary sampled video frames; no durable hero generated" },
  "Animation - Vintage Banned Cartoons.mp4": { headline: "The Complicated Afterlife of Vintage Cartoons", article: "The owned video is not a normal song subject, and the honest editorial move is to say so. “Vintage Banned Cartoons” describes a context collection rather than a single canonical recording. A future feature can investigate the cartoons actually present, but until those titles are established it should stay broad: animation has often carried changing standards about race, taste, violence, and acceptable public memory. The article must not assign a specific studio, character, ban, or controversy without evidence from the video and reliable research. Treating the file as a context subject preserves its usefulness while avoiding a false Song identity.", sources: ["https://en.wikipedia.org/wiki/Censored_Eleven", "https://commons.wikimedia.org/wiki/Category:Cartoons_about_censorship"], hero: "temporary sampled video frames; no durable hero generated" },
};

async function main() {
  const pilot = JSON.parse(await readFile(PILOT, "utf8")) as { records: any[] };
  const media = JSON.parse(await readFile(MEDIA, "utf8")) as { records: any[] };
  const manifest = JSON.parse(await readFile(MANIFEST, "utf8")) as { records: any[]; [key: string]: any };
  const mediaByPath = new Map(media.records.map((row) => [row.videoPath, row]));
  const subjectRows = pilot.records.map((row) => {
    const mediaRow = mediaByPath.get(row.normalizedPath ?? row.videoPath);
    const artist = String(row.vdjArtist ?? "").trim();
    const title = String(row.vdjTitle ?? "").trim();
    const usable = Boolean(artist && title);
    const context = mediaRow?.mediaClassification ?? "UNCERTAIN";
    const bobRequired = !usable;
    const classification = bobRequired ? "BOB_REVIEW_REQUIRED" : special.has(context) ? "SPECIAL_CONTEXT_RESEARCHABLE" : "EDITORIAL_RESEARCHABLE";
    return { videoPath: row.videoPath, vdjArtist: artist, vdjTitle: title, vdjAlbum: row.vdjAlbum ?? null, vdjYear: row.vdjYear ?? null, videoExperienceId: row.videoExperienceId, editorialSubject: usable ? `${artist} — ${title}` : null, contextualTerms: [artist, title, row.vdjAlbum, context].filter(Boolean), canonicalEnrichmentAvailable: Boolean(row.rvtr), canonicalRvtr: row.rvtr ?? null, chartJourneyAvailable: Boolean(row.chartRelationships?.length), researchQuery: [artist, title, row.vdjAlbum, context === "VERSION_OR_PERFORMANCE" ? row.performanceContext : null].filter(Boolean).join(" + "), collectorStatus: bobRequired ? "BLOCKED" : "RESEARCH_REQUIRED", editorialStatus: bobRequired ? "BLOCKED" : "RESEARCH_REQUIRED", heroStatus: "PREPARATION_REQUIRED", relatedMusicStatus: "PREPARATION_REQUIRED", validationStatus: "NOT_VALIDATED", classification, bobReviewRequired: bobRequired, bobReason: bobRequired ? "VDJ artist/title metadata is missing or unusable; no truthful editorial subject can be formed." : null, mediaClassification: context, underlyingSongRelationships: row.underlyingSongRelationships ?? [], sourceProvenance: ["VDJ metadata", "canonical-optional completion manifest", "media-aware classification manifest"] };
  });
  const updatedManifest = { ...manifest, version: 3, generatedAt: new Date().toISOString(), records: manifest.records.map((record) => { const subject = subjectRows.find((row) => row.videoPath === record.normalizedPath); if (!subject) return record; return { ...record, editorialSubject: subject.editorialSubject ? { artist: subject.vdjArtist, title: subject.vdjTitle, album: subject.vdjAlbum, year: subject.vdjYear } : null, editorialClassification: subject.classification, researchQuery: subject.researchQuery, bobReviewRequired: subject.bobReviewRequired, bobReason: subject.bobReason, collectorStatus: subject.collectorStatus, editorialStatus: subject.editorialStatus, overallStatus: subject.bobReviewRequired ? "IDENTITY_REQUIRED" : "RESEARCH_REQUIRED", preparationNeeds: subject.bobReviewRequired ? ["identity"] : ["editorial-research", "collector", "editorial", "hero", "relatedMusic", "validation"] }; }) };
  await writeFile(MANIFEST, JSON.stringify(updatedManifest, null, 2) + "\n");
  await mkdir(OUT, { recursive: true });
  const counts = Object.fromEntries(["EDITORIAL_READY_FROM_EXISTING", "EDITORIAL_RESEARCHABLE", "SPECIAL_CONTEXT_RESEARCHABLE", "BOB_REVIEW_REQUIRED", "BLOCKED"].map((key) => [key, subjectRows.filter((row) => row.classification === key).length]));
  await writeFile(join(OUT, "editorial-subject-manifest.json"), JSON.stringify({ version: 1, scope: "same-50", generatedAt: new Date().toISOString(), records: subjectRows, counts }, null, 2) + "\n");
  await writeFile(join(OUT, "bob-review-exceptions.json"), JSON.stringify({ version: 1, records: subjectRows.filter((row) => row.bobReviewRequired) }, null, 2) + "\n");
  await writeFile(join(OUT, "same-50-results.md"), `# Editorial-First Completion — Same 50\n\nPrevious BobOS queue: **41**. New Bob-required queue: **${subjectRows.filter((row) => row.bobReviewRequired).length}**.\n\n${Object.entries(counts).map(([key, value]) => `- ${key}: ${value}`).join("\n")}\n\nCanonical enrichment available: ${subjectRows.filter((row) => row.canonicalEnrichmentAvailable).length}. Chart Journey available: ${subjectRows.filter((row) => row.chartJourneyAvailable).length}. Research required: ${subjectRows.filter((row) => !row.bobReviewRequired).length}.\n\nA clear VDJ subject is not blocked by absent RVTR, album, year, or chart data. Unsupported exact performer/version claims remain excluded.\n`);
  await writeFile(join(OUT, "architecture-report.md"), `# Editorial-First VIDEO Completion Architecture\n\nVDJ artist/title metadata establishes an Editorial Subject, not a canonical identity. Canonical RVTR, chart, album, and exact-performance data remain optional enrichment.\n\nThe completion manifest now records editorialSubject, editorialClassification, researchQuery, bobReviewRequired, and separate Collector/editorial lifecycle states. A usable subject moves to RESEARCH_REQUIRED rather than IDENTITY_REQUIRED. Only missing/meaningless subject metadata or consequential conflict remains a BobOS exception.\n\nThe existing VDJ-only route remains the public fallback. Collector packets must distinguish supported facts, context, and uncertain claims. The Editor writes one cohesive magazine feature from the packet; it does not invent missing facts. Chart Journey appears only when a valid relationship exists. Related Music remains owned-video-only.\n\nFuture intake now establishes a subject from new VDJ metadata without creating a daemon or broad processor.\n`);
  const proofRows = subjectRows.filter((row) => proofs[`${row.vdjArtist} - ${row.vdjTitle}.mp4`] || proofs[`${row.vdjArtist} - ${row.vdjTitle}.mp4`.replace("Rhapsody in Blue", "Rhapsody In Blue")]);
  const proofOutput = Object.entries(proofs).map(([filename, proof]) => { const row = subjectRows.find((candidate) => String(candidate.videoPath).toLowerCase().endsWith(filename.toLowerCase())); return { filename, editorialSubject: row?.editorialSubject ?? filename.replace(/\.mp4$/i, ""), classification: row?.classification ?? "SPECIAL_CONTEXT_RESEARCHABLE", collectorPacket: { supportedFacts: proof.article, sources: proof.sources, uncertainClaims: ["Exact owned recording/performance identity is not asserted unless independently proven."] }, headline: proof.headline, article: proof.article, sources: proof.sources, heroResult: proof.hero, chartJourney: row?.chartJourneyAvailable ? "preserved when valid" : "omitted", relatedMusic: "not generated in broad scope; future owned-video recommendations use videoExperienceId", arvey: "existing Ask Arvey context can receive editorial subject", route: row?.mediaClassification === "NON_SONG_CONTEXT" ? null : row?.videoExperienceId?.startsWith("VDJ:") ? `/song/vdj/${row.videoExperienceId.slice(4)}` : row?.canonicalRvtr ? `/retroverse-2/song/${row.canonicalRvtr}` : null }; });
  await writeFile(join(OUT, "five-proof-report.md"), `# Five Editorial-First Proofs\n\n${proofOutput.map((proof) => `## ${proof.headline}\n\n- Subject: ${proof.editorialSubject}\n- Classification: ${proof.classification}\n- Route: ${proof.route ?? "pending subject identity"}\n- Hero: ${proof.heroResult}\n- Chart Journey: ${proof.chartJourney}\n- Related Music: ${proof.relatedMusic}\n- Headline: ${proof.headline}\n\n${proof.article}\n\nSources: ${proof.sources.join(", ")}\n`).join("\n")}`);
  console.log(JSON.stringify({ total: subjectRows.length, counts, previousBobQueue: 41, newBobQueue: subjectRows.filter((row) => row.bobReviewRequired).length, proofCount: proofOutput.length }));
}
void main().catch((error) => { console.error(error); process.exitCode = 1; });
