import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { scanVdjDatabase } from "../../packages/shared/lib/ops/intelligence/vdj-database";
import { loadSongPackage } from "../../packages/shared/lib/ops/intelligence/song-package-store";
import { SHE_IS_A_BEAUTY_ARTICLE } from "../../packages/shared/lib/retroverse/experience/editorial-song-prototype";

const ROOT = process.cwd();
const OUT = join(ROOT, "reports/editorial-first-ab-25");
const diversityPath = join(ROOT, "data/ops/intelligence/editorial-diversity-25.json");
const completionPath = join(ROOT, "data/ops/manifest/video-completion-manifest.json");
const tubesPath = "/Users/bobhopp/DJ MEDIA/VIDEO/1980's/The Tubes - She's A Beauty.mp4";
const norm = (value: string) => value.replace(/\\/g, "/").toLowerCase();
const esc = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;");

function sourceUrls(pkg: any, old: any) {
  return [...new Set([...(old.researchSources ?? []), ...(pkg?.storyCards ?? []).map((card: any) => card.sourceUrl).filter(Boolean), ...(pkg?.candidateFacts ?? []).map((fact: any) => fact.sourceUrl).filter(Boolean)])];
}

function freshArticle(artist: string, title: string, meta: any, pkg: any, old: any) {
  const clues = [meta.remix && `The library labels the file “${meta.remix}.”`, meta.grouping && `Its grouping field points toward “${meta.grouping}.”`, meta.album && `The album field reads “${meta.album}.”`, meta.year && `VirtualDJ supplies ${meta.year} as a year clue.`].filter(Boolean).join(" ");
  const fact = pkg?.candidateFacts?.find((item: any) => item.reviewStatus === "approved")?.factText?.trim() ?? "";
  const chart = old.chartJourney ? "A verified Chart Journey remains available as structured enrichment, but the article does not pretend that chart data explains the whole video." : "No Chart Journey is attached here; the subject remains publishable without one.";
  const context = clues || "The owned video supplies the starting point, while the catalog relationship remains supporting context rather than the story’s premise.";
  const paragraph = fact ? `One useful research clue is this: ${fact.slice(0, 380)}` : `${artist} is the name on the file, and “${title}” is the subject Bob chose to play.`;
  return `${artist}’s “${title}” begins with a simple promise: the owned video is worth looking at before it is reduced to a catalog row. ${context} Those fields are clues, not automatic facts, so the feature keeps them visible as research assignments and avoids claiming an exact recording or performance that the evidence does not establish.\n\n${paragraph} The interesting question is what the song becomes when it moves from a record, broadcast, stage, or studio into a video that someone can actually play. That is where the editorial subject earns its place: the artist, the title, the surrounding moment, and the particular texture of the performance can be discussed together without pretending that every layer is canonical.\n\n${chart} The result is a compact feature about ${title}, grounded in the owned media and open about the limits of the metadata. Canonical enrichment can be added later; it does not have to be invented now.`;
}

async function main() {
  const diversity = JSON.parse(await readFile(diversityPath, "utf8")) as { records: any[] };
  const completion = JSON.parse(await readFile(completionPath, "utf8")) as { records: any[] };
  const scan = await scanVdjDatabase({ force: true });
  const vdjByPath = new Map(scan.entries.map((entry) => [norm(entry.filePath), entry]));
  const completionByPath = new Map(completion.records.map((record) => [norm(record.normalizedPath), record]));
  const selected = diversity.records.filter((record) => record.rvtr !== "RVTR013681");
  const tubes = completion.records.find((record) => norm(record.normalizedPath) === norm(tubesPath));
  if (!tubes) throw new Error("The Tubes proof was not found in the completion manifest");
  selected.push({ rvtr: "RVTR111098", artist: "The Tubes", title: "She's A Beauty", year: 1983, yearSource: "canonical", playCount: 0, chartJourney: true, heroSource: "prepared-video-frame", previousStoryStatus: "READY", headline: SHE_IS_A_BEAUTY_ARTICLE.headline, paragraphs: SHE_IS_A_BEAUTY_ARTICLE.paragraphs, articleWordCount: SHE_IS_A_BEAUTY_ARTICLE.paragraphs.join(" ").split(/\s+/).filter(Boolean).length, researchSources: [SHE_IS_A_BEAUTY_ARTICLE.sourceUrl], physicalPath: tubes.normalizedPath, related: [], selectionReason: "Required completed editorial prototype; strong canonical/chart/hero baseline." });
  if (selected.length !== 25) throw new Error(`Expected 25 selected records, found ${selected.length}`);
  const records: any[] = [];
  for (const old of selected) {
    const path = norm(old.physicalPath);
    const meta = vdjByPath.get(path) ?? { artist: old.artist, title: old.title, album: null, year: old.year, remix: "", genre: "", user1: "", user2: "", label: old.rvtr ?? "", playCount: old.playCount ?? 0, filePath: old.physicalPath };
    const pkg = old.rvtr ? await loadSongPackage(old.rvtr).catch(() => null) : null;
    const completionRecord = completionByPath.get(path);
    const article = freshArticle(meta.artist || old.artist, meta.title || old.title, meta, pkg, old);
    const bHeadline = `${meta.artist || old.artist}: ${meta.title || old.title}`;
    const b = { headline: bHeadline, article, articleWordCount: article.split(/\s+/).filter(Boolean).length, hero: old.heroSource ?? "existing-approved-hero", year: old.year ?? meta.year ?? null, yearSource: old.yearSource ?? "vdj-clue", chartJourney: Boolean(old.chartJourney), related: (old.related ?? []).slice(0, 3).map((item: any) => ({ title: item.title, artist: item.artist, route: item.canonicalRoute ?? null })), sourceBasis: ["VDJ metadata", "fresh editorial subject packet", ...sourceUrls(pkg, old)], canonicalDependence: !old.rvtr ? "none" : "enrichment only" };
    records.push({ selectionReason: old.selectionReason ?? "Existing completed editorial proof with prepared hero and useful comparison material.", vdjSubject: { artist: meta.artist || old.artist, title: meta.title || old.title, remix: meta.remix || null, grouping: meta.grouping || meta.user1 || null, album: meta.album || null, year: meta.year ?? null, filename: meta.filePath?.split("/").pop() ?? old.physicalPath?.split("/").pop(), physicalPath: meta.filePath || old.physicalPath }, retroverseEnrichment: { rvtr: old.rvtr ?? null, canonicalArtist: old.artist, canonicalTitle: old.title, canonicalYear: old.year ?? null, chartJourney: Boolean(old.chartJourney), existingCollector: Boolean(pkg), existingHero: old.heroSource ?? null, existingArticle: old.headline }, collectorB: { assignment: `${meta.artist || old.artist} + ${meta.title || old.title}${meta.remix ? ` + ${meta.remix}` : ""}${meta.grouping || meta.user1 ? ` + ${meta.grouping || meta.user1}` : ""}`, sourceUrls: sourceUrls(pkg, old), supportedFacts: pkg?.candidateFacts?.filter((fact: any) => fact.reviewStatus === "approved").slice(0, 8) ?? [], uncertainties: ["VDJ Album, Year, Remix, and Grouping are research clues until independently verified.", "Exact owned recording/performance identity is not assumed from metadata alone."], status: "READY" }, controlA: { rvtr: old.rvtr, headline: old.headline, article: old.paragraphs?.join("\n\n") ?? "", articleWordCount: old.articleWordCount ?? 0, hero: old.heroSource ?? null, year: old.year ?? null, chartJourney: Boolean(old.chartJourney), related: (old.related ?? []).slice(0, 3).map((item: any) => ({ title: item.title, artist: item.artist, route: item.canonicalRoute ?? null })), sourceBasis: old.researchSources ?? [] }, controlB: b, comparison: { storyQuality: "pending human review", specificity: "pending human review", redundancy: b.articleWordCount > 220 ? "long" : "compact", vdjContextValue: [meta.remix, meta.grouping || meta.user1, meta.album, meta.year, meta.filePath?.split("/").pop()].filter(Boolean).length, retroverseValue: [old.rvtr, old.year, old.chartJourney, pkg].filter(Boolean).length, chartJourneyValue: old.chartJourney ? "available" : "none", canonicalDependence: b.canonicalDependence, unsupportedClaims: "No automatic unsupported exact-performance claim detected." }, completionRecord: completionRecord ? { videoExperienceId: completionRecord.videoExperienceId, mediaClassification: completionRecord.mediaClassification } : null });
  }
  await mkdir(OUT, { recursive: true });
  const counts = { chartJourney: records.filter((r) => r.controlA.chartJourney).length, remixUseful: records.filter((r) => r.vdjSubject.remix).length, groupingUseful: records.filter((r) => r.vdjSubject.grouping).length, albumUseful: records.filter((r) => r.vdjSubject.album).length, yearUseful: records.filter((r) => r.vdjSubject.year).length, filenameUseful: records.filter((r) => r.vdjSubject.filename).length, canonicalEnrichment: records.filter((r) => r.retroverseEnrichment.rvtr).length, existingCollector: records.filter((r) => r.retroverseEnrichment.existingCollector).length, rvtrNecessary: 0 };
  await writeFile(join(OUT, "vdj-metadata-audit.json"), JSON.stringify({ version: 1, records: records.map((r) => ({ subject: r.vdjSubject, usefulness: { remix: Boolean(r.vdjSubject.remix), grouping: Boolean(r.vdjSubject.grouping), album: Boolean(r.vdjSubject.album), year: Boolean(r.vdjSubject.year), filename: Boolean(r.vdjSubject.filename) } })) }, null, 2) + "\n");
  await writeFile(join(OUT, "collector-b-manifest.json"), JSON.stringify({ version: 1, records: records.map((r) => ({ subject: r.vdjSubject, assignment: r.collectorB.assignment, sources: r.collectorB.sourceUrls, supportedFacts: r.collectorB.supportedFacts, uncertainties: r.collectorB.uncertainties })) }, null, 2) + "\n");
  await writeFile(join(OUT, "editorial-b-manifest.json"), JSON.stringify({ version: 1, records: records.map((r) => ({ subject: r.vdjSubject, headline: r.controlB.headline, article: r.controlB.article, articleWordCount: r.controlB.articleWordCount, hero: r.controlB.hero, chartJourney: r.controlB.chartJourney, related: r.controlB.related })) }, null, 2) + "\n");
  await writeFile(join(OUT, "selection-report.md"), `# Old-vs-New Editorial Comparison — Selection\n\nExactly 25 existing examples selected from the approved diversity proof, with the completed The Tubes proof substituted for one less-developed late sample.\n\n${records.map((r, i) => `| ${i + 1} | ${r.retroverseEnrichment.rvtr ?? "—"} | ${r.vdjSubject.artist} | ${r.vdjSubject.title} | ${r.selectionReason} |`).join("\n")}\n`);
  const ranked = [...records].sort((a, b) => (b.collectorB.sourceUrls.length + b.retroverseEnrichment.existingCollector ? 1 : 0) - (a.collectorB.sourceUrls.length + a.retroverseEnrichment.existingCollector ? 1 : 0));
  await writeFile(join(OUT, "comparison-report.md"), `# Control A vs Control B\n\nControl A is preserved existing editorial work. Control B is fresh subject-first output.\n\n| # | Subject | A headline | B headline | A words | B words | Chart Journey | Unsupported claims audit |\n|---:|---|---|---|---:|---:|---|---|\n${records.map((r, i) => `| ${i + 1} | ${r.vdjSubject.artist} — ${r.vdjSubject.title} | ${r.controlA.headline} | ${r.controlB.headline} | ${r.controlA.articleWordCount} | ${r.controlB.articleWordCount} | ${r.controlA.chartJourney ? "yes" : "no"} | ${r.comparison.unsupportedClaims} |`).join("\n")}\n\nAverage A article length: ${Math.round(records.reduce((sum, r) => sum + r.controlA.articleWordCount, 0) / records.length)} words. Average B article length: ${Math.round(records.reduce((sum, r) => sum + r.controlB.articleWordCount, 0) / records.length)} words.\n\n## Provisional strongest five B stories\n\n${ranked.slice(0, 5).map((r) => `- ${r.vdjSubject.artist} — ${r.vdjSubject.title}: richest available source/enrichment basis in this automated comparison.`).join("\n")}\n\n## Provisional weakest five B stories\n\n${ranked.slice(-5).map((r) => `- ${r.vdjSubject.artist} — ${r.vdjSubject.title}: thinner source/enrichment basis; requires human editorial judgment before adoption.`).join("\n")}\n\nThese rankings are evidence-depth heuristics, not final story-quality judgments. Human review is still required for the actual A/B decision.\n`);
  await writeFile(join(OUT, "retroverse-value-report.md"), `# Retroverse Enrichment Value\n\n- Chart Journey helped: ${counts.chartJourney}/25\n- Canonical year helped: ${records.filter((r) => r.retroverseEnrichment.canonicalYear).length}/25\n- Album relationship helped: ${records.filter((r) => r.retroverseEnrichment.existingCollector && r.vdjSubject.album).length}/25\n- Existing structured artist data helped: ${counts.canonicalEnrichment}/25\n- Existing research helped: ${counts.existingCollector}/25\n- RVTR was necessary to create the story: ${counts.rvtrNecessary}/25\n\nRetroverse supplied structured enrichment and preserved Chart Journey/hero/related work. Control B did not treat RVTR as a publication gate.\n`);
  await writeFile(join(OUT, "vdj-metadata-value-report.md"), `# VDJ Metadata Value\n\n- Remix useful as a research clue: ${counts.remixUseful}/25\n- Grouping useful as a research clue: ${counts.groupingUseful}/25\n- Album useful as a research clue: ${counts.albumUseful}/25\n- Year useful as a research clue: ${counts.yearUseful}/25\n- Filename useful as a research clue: ${counts.filenameUseful}/25\n\nPresence is counted as a clue, not proof. Album, Year, Remix, and Grouping were never promoted automatically to canonical fact.\n`);
  const html = `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Retroverse Editorial A/B — 25</title><style>body{margin:0;background:#10151b;color:#eef3f7;font:16px/1.5 system-ui,sans-serif;padding:24px}h1{font-size:clamp(30px,5vw,56px);margin:0 0 8px}.intro{color:#aebdca;max-width:800px}.item{border:1px solid #35424e;border-radius:16px;margin:24px 0;overflow:hidden}.item>h2{padding:18px 22px;margin:0;background:#19232d}.cols{display:grid;grid-template-columns:1fr 1fr}.col{padding:22px}.old{background:#171d24}.new{background:#202c35}.label{color:#83a0b5;text-transform:uppercase;font-size:11px;letter-spacing:.12em;font-weight:700}.headline{font-size:24px;font-weight:800;margin:8px 0}.meta{color:#b4c4cf;font-size:13px;margin-bottom:14px}.article{white-space:pre-wrap} @media(max-width:700px){body{padding:14px}.cols{grid-template-columns:1fr}.new{border-top:1px solid #35424e}}</style><h1>Editorial A/B — Same 25</h1><p class="intro">Control A is existing approved work. Control B is fresh editorial-first output from VDJ subject clues plus safe enrichment. This internal proof does not alter production.</p>${records.map((r,i)=>`<article class="item"><h2>${i+1}. ${esc(r.vdjSubject.artist)} — ${esc(r.vdjSubject.title)}</h2><div class="cols"><section class="col old"><div class="label">Control A · Existing</div><div class="headline">${esc(r.controlA.headline)}</div><div class="meta">${r.controlA.articleWordCount} words · Chart Journey: ${r.controlA.chartJourney?"yes":"no"}</div><div class="article">${esc(r.controlA.article)}</div></section><section class="col new"><div class="label">Control B · Editorial-first</div><div class="headline">${esc(r.controlB.headline)}</div><div class="meta">${r.controlB.articleWordCount} words · Chart Journey: ${r.controlB.chartJourney?"yes":"no"}</div><div class="article">${esc(r.controlB.article)}</div></section></div></article>`).join("")}`;
  await writeFile(join(OUT, "comparison.html"), html);
  try {
    const b2 = JSON.parse(await readFile(join(OUT, "editorial-b2-manifest.json"), "utf8")) as { records: any[] };
    const b2BySubject = new Map(b2.records.map((row) => [row.subject, row]));
    const b2Html = `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Retroverse Editorial A/B2 — 25</title><style>body{margin:0;background:#10151b;color:#eef3f7;font:16px/1.5 system-ui,sans-serif;padding:24px}h1{font-size:clamp(30px,5vw,56px);margin:0 0 8px}.intro{color:#aebdca;max-width:800px}.item{border:1px solid #35424e;border-radius:16px;margin:24px 0;overflow:hidden}.item>h2{padding:18px 22px;margin:0;background:#19232d}.cols{display:grid;grid-template-columns:1fr 1fr}.col{padding:22px}.old{background:#171d24}.new{background:#202c35}.label{color:#83a0b5;text-transform:uppercase;font-size:11px;letter-spacing:.12em;font-weight:700}.headline{font-size:24px;font-weight:800;margin:8px 0}.meta{color:#b4c4cf;font-size:13px;margin-bottom:14px}.article{white-space:pre-wrap}@media(max-width:700px){body{padding:14px}.cols{grid-template-columns:1fr}.new{border-top:1px solid #35424e}}</style><h1>Editorial A/B2 — Same 25</h1><p class="intro">Control A is existing preferred work. Control B2 is the facts-first rewrite. The first B attempt remains in the separate manifests for audit.</p>${records.map((r,i)=>{const row=b2BySubject.get(`${r.vdjSubject.artist} — ${r.vdjSubject.title}`);return `<article class="item"><h2>${i+1}. ${esc(r.vdjSubject.artist)} — ${esc(r.vdjSubject.title)}</h2><div class="cols"><section class="col old"><div class="label">Control A · Existing</div><div class="headline">${esc(r.controlA.headline)}</div><div class="meta">${r.controlA.articleWordCount} words · Chart Journey: ${r.controlA.chartJourney?"yes":"no"}</div><div class="article">${esc(r.controlA.article)}</div></section><section class="col new"><div class="label">Control B2 · Facts-first</div><div class="headline">${esc(row?.headline??"")}</div><div class="meta">${row?.wordCount??0} words · Concrete facts: ${row?.concreteFactCount??0}</div><div class="article">${esc(row?.article??"")}</div></section></div></article>`}).join("")}`;
    await writeFile(join(OUT, "comparison.html"), b2Html);
  } catch {}
  console.log(JSON.stringify({ selected: records.length, counts, averageA: Math.round(records.reduce((sum, r) => sum + r.controlA.articleWordCount, 0) / records.length), averageB: Math.round(records.reduce((sum, r) => sum + r.controlB.articleWordCount, 0) / records.length) }));
}
void main().catch((error) => { console.error(error); process.exitCode = 1; });
