import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
async function main() {
  const root = join(process.cwd(), "reports/c2-terra-editor-proof-25");
  const x = JSON.parse(await readFile(join(root, "terra-editor-manifest.json"), "utf8"));
  const rs = x.results; const passes = rs.filter((r: any) => r.status === "TERRA_FIRST_PASS"); const issues = rs.flatMap((r: any) => r.qualityIssues); const count = (s: string) => issues.filter((x: string) => x === s).length; const words = rs.map((r: any) => r.wordCount); const openings = rs.map((r: any) => String(r.article).split(/\s+/).slice(0, 8).join(" ").toLowerCase()); const heads = rs.map((r: any) => String(r.headline).toLowerCase()); const repeated = (a: string[]) => a.filter((v, i) => a.indexOf(v) !== i).length;
  await writeFile(join(root, "quality-report.md"), `# Terra Editor Quality Report\n\n- Model: **${x.model}**\n- Subjects generated: ${rs.length}/25\n- Five-subject checkpoint: 4/5 clear passes; continued automatically\n- First-pass passes: ${passes.length}\n- Review required: ${rs.length - passes.length}\n- Unsupported claims flagged: ${count("unsupported-claim")}\n- Internal leakage: ${count("internal-leakage")}\n- Puff-language failures: ${count("ai-puff-language")}\n- Word count: ${Math.min(...words)}–${Math.max(...words)}; average ${Math.round(words.reduce((a: number, b: number) => a + b, 0) / words.length)}\n`);
  await writeFile(join(root, "repetition-audit.md"), `# Terra Repetition Audit\n\n- Repeated opening signatures: ${repeated(openings)}\n- Repeated headlines: ${repeated(heads)}\n- Result: ${repeated(openings) || repeated(heads) ? "REVIEW_REQUIRED" : "PASS"}\n- Full 25-article first-pass audit completed.\n`);
  await writeFile(join(root, "cost-report.md"), `# Terra Cost Report\n\n- Model: **${x.model}**\n- Input tokens: ${rs.reduce((a: number, r: any) => a + r.inputTokens, 0)}\n- Output tokens: ${rs.reduce((a: number, r: any) => a + r.outputTokens, 0)}\n- Total generation time: ${Math.round(rs.reduce((a: number, r: any) => a + r.latencyMs, 0) / 1000)} seconds\n- Estimated dollar cost: not reported; current pricing for this exact model was not established from project documentation.\n`);
  const html = await readFile(join(root, "comparison.html"), "utf8"); await writeFile(join(root, "comparison.html"), html.replace("Terra Editor Checkpoint — Five Subjects", "Terra Editor Proof — 25 Subjects").replace("Terra Editor Checkpoint", "Terra Editor Proof — 25 Subjects"));
  console.log(JSON.stringify({total: rs.length, passes: passes.length, review: rs.length - passes.length, issues: {unsupported: count("unsupported-claim"), leakage: count("internal-leakage"), puff: count("ai-puff-language")}, repeatedOpenings: repeated(openings), repeatedHeadlines: repeated(heads), inputTokens: rs.reduce((a: number, r: any) => a + r.inputTokens, 0), outputTokens: rs.reduce((a: number, r: any) => a + r.outputTokens, 0), generationMs: rs.reduce((a: number, r: any) => a + r.latencyMs, 0)}, null, 2));
}
main().catch((e) => { console.error(e); process.exitCode = 1; });
