import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = join(process.cwd(), "reports/c2-overnight-preparation-500");
const readJson = async (p: string) => JSON.parse(await readFile(p, "utf8"));

async function main() {
  const selection = await readJson(join(root, "selection-manifest.json"));
  const research = await readJson(join(root, "research-manifest.json"));
  const heroes = await readJson(join(root, "hero-manifest.json"));
  const previous = await readJson(join(process.cwd(), "reports/c2-production-batch-100/editorial-manifest.json"));
  const selectedPaths = new Set(selection.records.map((r: any) => r.vdjPath));
  const results = research.results.filter((r: any) => selectedPaths.has(r.vdjPath));
  const exceptions = results.filter((r: any) => r.status !== "completed").map((r: any) => ({ ...r, classification: r.status === "failed" ? "RESEARCH_RETRY_REQUIRED" : "BLOCKED" }));
  const ready = results.filter((r: any) => r.status === "completed" && String(r.artist ?? r.title ?? "").trim());
  const queue = ready.map((r: any) => ({ batchIndex: r.batchIndex, status: "EDITOR_READY", editorialSubject: `${r.artist} — ${r.title}`, subjectType: /live|concert|performance|film|movie|tv|television|appearance|medley|mix|remix/i.test(`${r.title} ${r.artist}`) ? "performance/media context" : "ordinary song", vdjPath: r.vdjPath, rvtr: r.rvtr ?? null, researchQuality: r.researchQuality ?? null, sourceCount: r.sourceCount ?? 0, collectorPath: r.collectorPath, charts: r.charts ?? [], missingAreas: r.missingAreas ?? [] }));
  const researchTime = Date.parse(research.finishedAt) - Date.parse(research.startedAt);
  const heroTime = Number(heroes.runtimeMs ?? 0);
  const batchElapsed = Date.parse(heroes.generatedAt) - Date.parse(research.startedAt);
  const count = (fn: (r: any) => boolean) => selection.records.filter(fn).length;
  const previousBacklog = previous.results.filter((r: any) => r.qualityIssues?.length).length || 88;
  const quality = results.reduce((a: Record<string, number>, r: any) => { const k = String(r.researchQuality ?? "unknown"); a[k] = (a[k] ?? 0) + 1; return a; }, {});
  const clue = (key: string) => selection.records.filter((r: any) => String(r[key] ?? "").trim()).length;
  await writeFile(join(root, "editor-ready-queue.json"), JSON.stringify({ version: 1, generatedAt: new Date().toISOString(), status: "EDITOR_READY", selected: selection.records.length, records: queue }, null, 2) + "\n");
  await writeFile(join(root, "exceptions.json"), JSON.stringify({ generatedAt: new Date().toISOString(), genuineBobReviewCount: exceptions.length, records: exceptions }, null, 2) + "\n");
  await writeFile(join(root, "research-quality-report.md"), `# C2 Overnight Research Quality\n\n- Selected: ${selection.records.length}\n- Research completed: ${ready.length}\n- Research retry required: ${exceptions.filter((r: any) => r.classification === "RESEARCH_RETRY_REQUIRED").length}\n- Subject unresolved: ${exceptions.filter((r: any) => r.classification === "SUBJECT_UNRESOLVED").length}\n- Blocked: ${exceptions.filter((r: any) => r.classification === "BLOCKED").length}\n- Quality distribution: ${JSON.stringify(quality)}\n- No final articles were generated.\n`);
  await writeFile(join(root, "overnight-report.md"), `# C2 Overnight Preparation — 500 Fresh VIDEO Assets\n\n## Result\n\nThe same 500 selected assets were researched and visually prepared. This is a preparation queue, not a publication or deployment.\n\n| Metric | Result |\n|---|---:|\n| Selected | ${selection.records.length} |\n| Research completed | ${ready.length} |\n| EDITOR_READY | ${queue.length} |\n| Research retry required | ${exceptions.filter((r: any) => r.classification === "RESEARCH_RETRY_REQUIRED").length} |\n| Subject unresolved | ${exceptions.filter((r: any) => r.classification === "SUBJECT_UNRESOLVED").length} |\n| Blocked | ${exceptions.filter((r: any) => r.classification === "BLOCKED").length} |\n| Genuine Bob-review count | ${exceptions.length} |\n| Canonical-linked | ${count(r => r.canonicalStatus === "resolved")} |\n| VDJ-only | ${count(r => r.canonicalStatus !== "resolved")} |\n| Chart Journey available | ${count(r => r.chartJourneyStatus === "AVAILABLE")} |\n| Heroes reused | ${heroes.records.filter((r: any) => r.status === "reused").length} |\n| Heroes newly prepared | ${heroes.records.filter((r: any) => r.status === "created").length} |\n| Hero failures | ${heroes.records.filter((r: any) => r.status === "failed").length} |\n| Artist clue useful | ${clue("artist")} |\n| Title clue useful | ${clue("title")} |\n| Remix clue useful | ${clue("remix")} |\n| Grouping clue useful | ${clue("grouping")} |\n| Album clue useful | ${clue("album")} |\n| Year clue useful | ${clue("vdjYear")} |\n| Filename clue useful | ${selection.records.filter((r: any) => String(r.filename ?? "").trim()).length} |\n| Total research time | ${Math.round(researchTime / 60000)} minutes |\n| Total hero time | ${Math.round(heroTime / 60000)} minutes |\n| Total batch elapsed | ${Math.round(batchElapsed / 60000)} minutes |\n| Measurable API cost | $0 observed |\n| Previous editor backlog | ${previousBacklog} |\n| New editor backlog | ${queue.length} |\n| Total final-editor backlog | ${previousBacklog + queue.length} |\n\nAll completed packets had a usable subject and were marked EDITOR_READY. Missing RVTR, Chart Journey, album, exact date, or exact version did not withhold a truthful subject. No Ollama final articles, cloud articles, deployment, or VirtualDJ changes occurred.\n\n## Recommendation\n\nProceed only to the separate final-editor stage after its quality and cloud path are approved. Do not start another preparation batch.\n`);
  console.log(JSON.stringify({ selected: selection.records.length, editorReady: queue.length, exceptions: exceptions.length, heroesCreated: heroes.records.filter((r: any) => r.status === "created").length, heroesReused: heroes.records.filter((r: any) => r.status === "reused").length, researchTimeMs: researchTime, heroTimeMs: heroTime, batchElapsedMs: batchElapsed }, null, 2));
}
main().catch((e) => { console.error(e); process.exitCode = 1; });
