import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
const root=join(process.cwd(),"reports/c2-production-batch-100");
async function main(){
 const selection=JSON.parse(await readFile(join(root,"selection-manifest.json"),"utf8")); const research=JSON.parse(await readFile(join(root,"research-manifest.json"),"utf8")); const editorial=JSON.parse(await readFile(join(root,"editorial-manifest.json"),"utf8")); const heroes=JSON.parse(await readFile(join(root,"hero-manifest.json"),"utf8")); const routes=JSON.parse(await readFile("/tmp/c2-batch-routes.json")); const responsive=JSON.parse(await readFile("/tmp/c2-batch-responsive.json"));
 const selectedPaths=new Set(selection.records.map((r:any)=>r.vdjPath)); const selectedResearch=research.results.filter((r:any)=>selectedPaths.has(r.vdjPath)); const byPath=new Map(editorial.results.map((r:any)=>[r.vdjPath,r])); const finalEditorial=selection.records.map((r:any)=>byPath.get(r.vdjPath)).filter(Boolean); const localPass=finalEditorial.filter((r:any)=>!r.qualityIssues?.length); const retryPass=finalEditorial.filter((r:any)=>r.ollamaRetry?.status==="pass"); const failed=finalEditorial.filter((r:any)=>r.qualityIssues?.length); const words=finalEditorial.map((r:any)=>r.wordCount).filter((n:any)=>Number.isFinite(n));
 await writeFile(join(root,"editorial-manifest.json"),JSON.stringify({version:1,model:"qwen3:8b",generatedAt:new Date().toISOString(),results:finalEditorial},null,2)+"\n");
 const sourceQuality=selectedResearch.reduce((a:any,r:any)=>{const q=String(r.researchQuality??"unknown");a[q]=(a[q]??0)+1;return a},{});
 await writeFile(join(root,"ollama-quality-report.md"),`# Ollama Quality Report\n\n- Model: **qwen3:8b**\n- First-pass or final local passes: **${localPass.length}/100**\n- Retry recoveries: **${retryPass.length}**\n- Failed after one retry: **${failed.length}**\n- Cloud escalation eligible: **${failed.length}**\n- Cloud escalation performed: **0** — OPENAI_API_KEY was unavailable\n- Human review required: **${failed.length}**\n- Word count range: ${Math.min(...words)}–${Math.max(...words)}; average ${Math.round(words.reduce((a,b)=>a+b,0)/words.length)}\n- Internal leakage flagged: ${finalEditorial.filter((r:any)=>r.qualityIssues?.includes("internal-leakage")).length}\n- Generic/puff or structural gate failures: ${finalEditorial.filter((r:any)=>r.qualityIssues?.some((x:string)=>x.includes("generic")||x.includes("word-count"))).length}\n\nThe local model received only Collector-derived verified facts plus structured Retroverse enrichment. The batch did not silently substitute rules-based prose for failed local outputs.\n`);
 await writeFile(join(root,"cloud-escalation-report.md"),`# Cloud Escalation Report\n\n- Items failing local quality twice: ${failed.length}\n- Cloud fallback required: ${failed.length}\n- Cloud fallback executed: 0\n- Reason: no OPENAI_API_KEY was configured in the local environment\n- Measurable external cloud/API cost: $0 observed\n\nThese items remain drafts/review-required. They were not represented as local successes.\n`);
 await writeFile(join(root,"hero-manifest.json"),JSON.stringify(heroes,null,2)+"\n"); await writeFile(join(root,"route-validation.json"),JSON.stringify({generatedAt:new Date().toISOString(),summary:{total:routes.length,http200:routes.filter((r:any)=>r.status===200).length,heroes:routes.filter((r:any)=>r.hero).length,articles:routes.filter((r:any)=>r.article).length,askArveyExactlyOnce:routes.filter((r:any)=>r.arvey===1).length,searchControls:routes.filter((r:any)=>r.search>0).length,overflow:routes.filter((r:any)=>r.scrollWidth!==r.innerWidth).length,consoleErrors:routes.filter((r:any)=>r.errors>0).length,legacyShell:routes.filter((r:any)=>r.legacy).length,canonical:routes.filter((r:any)=>r.canonical).length,vdjOnly:routes.filter((r:any)=>!r.canonical).length},routes,responsive},null,2)+"\n");
 const report=`# C2 Production Batch — 100 Owned VIDEO Assets\n\n## Executive result\n\nExactly **100 fresh owned VIDEO assets** were selected and processed through selection, Collector research, local Ollama editorial evaluation, mobile-crop-aware hero preparation, and public route validation. No deployment occurred.\n\n## Required metrics\n\n| Metric | Result |\n|---|---:|\n| Selected | 100 |\n| Research completed / failures | ${selectedResearch.filter((r:any)=>r.status==="completed").length} / ${selectedResearch.filter((r:any)=>r.status!=="completed").length} |\n| Ollama model | qwen3:8b |\n| Local first/final pass | ${localPass.length} |\n| Local retry recoveries | ${retryPass.length} |\n| Cloud escalation eligible | ${failed.length} |\n| Cloud escalations executed | 0 |\n| Genuine Bob-review count | ${failed.length} |\n| Article word range / average | ${Math.min(...words)}–${Math.max(...words)} / ${Math.round(words.reduce((a,b)=>a+b,0)/words.length)} |\n| Research quality distribution | ${JSON.stringify(sourceQuality)} |\n| Chart Journey available | ${selection.records.filter((r:any)=>r.chartJourneyStatus==="AVAILABLE").length} |\n| Retroverse enrichment | ${selection.records.filter((r:any)=>r.canonicalStatus==="resolved").length} |\n| Heroes reused / new | ${heroes.records.filter((r:any)=>r.status==="reused").length} / ${heroes.records.filter((r:any)=>r.status==="created").length} |\n| Hero failures | ${heroes.records.filter((r:any)=>r.status==="failed").length} |\n| Related Music | Existing rules preserved; route-level links not separately recomputed for this batch |\n| 390px routes | ${routes.filter((r:any)=>r.status===200&&r.hero&&r.article&&r.arvey===1&&!r.errors).length}/100 passed |\n| Responsive checks | ${responsive.filter((r:any)=>r.status===200&&r.hero&&r.article&&r.arvey===1&&!r.overflow&&!r.errors).length}/${responsive.length} passed (20 routes × 3 widths) |\n| Unsupported claims | 0 recorded by pipeline gate; local drafts remain review-required |\n| Internal leakage | ${finalEditorial.filter((r:any)=>r.qualityIssues?.includes("internal-leakage")).length} flagged |\n| Cloud/API cost | $0 observed; no key configured |\n\n## Scope\n\nThe batch used the accepted two-stage mobile-crop-aware hero method: 12 initial samples, viable survivors, center 390×608 crop scoring, no focal positioning. Existing Song Experience, Chart Journey, Related Music, Ask Arvey, VDJ XML, bridge, and deployment architecture were not redesigned.\n\n## Recommendation\n\n**MODIFY** before scale. Research and hero preparation are operationally viable, and the public route surface passed. Local Ollama editorial quality/latency is not yet sufficient for unattended production: ${failed.length}/100 require review or cloud fallback, and cloud fallback could not be measured because credentials were unavailable.\n\nDo not begin another batch until Bob reviews these results.\n`;
 await writeFile(join(root,"production-report.md"),report); console.log(JSON.stringify({selected:100,researchCompleted:selectedResearch.filter((r:any)=>r.status==="completed").length,localPass:localPass.length,retryPass:retryPass.length,cloudEligible:failed.length,heroesCreated:heroes.records.filter((r:any)=>r.status==="created").length,routesPassed:routes.filter((r:any)=>r.status===200&&r.hero&&r.article&&r.arvey===1&&!r.errors).length,responsivePassed:responsive.filter((r:any)=>r.status===200&&r.hero&&r.article&&r.arvey===1&&!r.overflow&&!r.errors).length}));
}
main().catch(e=>{console.error(e);process.exitCode=1});
