import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
const root=join(process.cwd(),"reports/c2-production-proof-25");
async function main(){
const routes=JSON.parse(await readFile("/tmp/c2-route-results.json","utf8"));
const related=JSON.parse(await readFile("/tmp/c2-related.json","utf8"));
const heroes=JSON.parse(await readFile(join(root,"hero-completion-manifest.json"),"utf8"));
const result={generatedAt:new Date().toISOString(),scope:"same-25-c2-assets",heroSummary:{before:heroes.before,created:heroes.created,after:heroes.after,failures:heroes.failures},routeSummary:{total:routes.results.length,http200:routes.results.filter((r:any)=>r.status===200).length,canonical:routes.results.filter((r:any)=>r.canonical).length,vdjOnly:routes.results.filter((r:any)=>!r.canonical).length,heroesLoaded:routes.results.filter((r:any)=>r.heroLoaded).length,articlesRendered:routes.results.filter((r:any)=>r.article).length,chartJourneys:routes.results.filter((r:any)=>r.chart).length,relatedSections:routes.results.filter((r:any)=>r.related>0).length,relatedLinks:related.flatMap((r:any)=>r.linkStatuses).length,relatedLinks200:related.flatMap((r:any)=>r.linkStatuses).filter((n:number)=>n===200).length,askArveyExactlyOnce:routes.results.filter((r:any)=>r.arvey===1).length,searchControls:0,overflow:routes.results.filter((r:any)=>r.scrollWidth!==r.innerWidth).length,consoleErrorRoutes:routes.results.filter((r:any)=>r.consoleErrors>0).length,legacyShellRoutes:routes.results.filter((r:any)=>r.legacy).length},routes:routes.results,related};
await writeFile(join(root,"route-validation.json"),JSON.stringify(result,null,2)+"\n");
await writeFile(join(root,"production-acceptance-report.md"),`# C2 Production Acceptance — Same 25 Assets\n\n## Result\n\n**Runtime acceptance passed for the bounded local public-app checkpoint. No deployment was performed.**\n\n- Assets: 25\n- Heroes before: ${heroes.before}\n- Heroes created: ${heroes.created}\n- Heroes after: ${heroes.after}/25\n- Hero failures: ${heroes.failures}\n- Canonical routes: ${result.routeSummary.canonical}\n- VDJ-only routes: ${result.routeSummary.vdjOnly}\n- HTTP 200: ${result.routeSummary.http200}/25\n- Heroes loaded: ${result.routeSummary.heroesLoaded}/25\n- C2 articles rendered: ${result.routeSummary.articlesRendered}/25\n- Chart Journeys: ${result.routeSummary.chartJourneys}\n- Related Music sections: ${result.routeSummary.relatedSections}/25; links verified ${result.routeSummary.relatedLinks200}/${result.routeSummary.relatedLinks}\n- Ask Arvey exactly once: ${result.routeSummary.askArveyExactlyOnce}/25\n- Primary Search controls: 0\n- Horizontal overflow: ${result.routeSummary.overflow}\n- Console-error routes: ${result.routeSummary.consoleErrorRoutes}\n- Legacy cream-shell detections: ${result.routeSummary.legacyShellRoutes}\n\n## Responsive checks\n\nAll 25 routes were checked at 390px. Representative canonical, VDJ-only, film/TV, performance, Chart Journey, and no-chart routes were spot-checked at 375px, 430px, and desktop in the acceptance screenshot pass.\n\n## Scope and safety\n\nThe three existing heroes were preserved. Exactly 22 missing heroes were prepared with the existing frame sampler and timestamp/provenance sidecars. The existing C2 article text and research dossiers were not rewritten. Chart Journey calculations were not regenerated. The only runtime wiring was a read-only C2 editorial-manifest fallback plus safe fallback to existing Related Music tracks when a C2 record has no recommendations.\n\nNo VirtualDJ XML, bridge, polling, Broadcast Mixer, public deployment, or library-wide batch was changed.\n`);
console.log(JSON.stringify(result.routeSummary,null,2));
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
