require("../finance/preload-server-only.cjs");
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";
import { sampleFrames } from "@/lib/ops/issue-generation/sample-frames";
import { collectorVisualAssetsDir } from "@/lib/studio/package";
const root = join(process.cwd(), "reports/c2-production-batch-100");
const W=390,H=608;
async function main(){ const s=JSON.parse(await readFile(join(root,"selection-manifest.json"),"utf8")); const records:any[]=[]; const started=Date.now();
 for(const [i,row] of s.records.entries()){ const identity=String(row.videoExperienceId??row.rvtr??`VDJ:${row.batchIndex}`).replace(/^VDJ:/i,"VDJ-").toUpperCase(); const dir=collectorVisualAssetsDir(identity); const existing=await readFile(join(dir,"hero-video.json"),"utf8").then(JSON.parse).catch(()=>null); if(existing?.sourceType==="prepared-video-frame" && row.heroStatus==="PREPARED_VIDEO_HERO"){records.push({batchIndex:row.batchIndex,identity,status:"reused",sourceVideo:row.vdjPath});continue;} const scratch=join(root,"hero-candidates",identity); const sampled=await sampleFrames(row.vdjPath,scratch); const crops=[]; for(let j=0;j<sampled.frames.length;j++){const out=join(scratch,`mobile-${j+1}.jpg`); const info=await sharp(sampled.frames[j]).resize(W,H,{fit:"cover",position:"centre"}).jpeg({quality:88}).toFile(out); const st=await sharp(out).stats(); const contrast=st.channels.reduce((n,c)=>n+c.stdev,0)/st.channels.length; const mean=st.channels.reduce((n,c)=>n+c.mean,0)/st.channels.length; crops.push({j,out,score:Math.max(0,100-Math.abs(mean-128)*.25)+Math.min(35,contrast),mean,contrast,dimensions:[info.width,info.height]});} crops.sort((a,b)=>b.score-a.score); const chosen=crops[0]; if(!chosen){records.push({batchIndex:row.batchIndex,identity,status:"failed",sourceVideo:row.vdjPath});continue;} await mkdir(dir,{recursive:true}); await copyFile(sampled.frames[chosen.j],join(dir,"hero-video.jpg")); const selectedSeconds=sampled.selection.selectedTimestamps[chosen.j]??null; const metadata={sourceVideo:row.vdjPath,selectedSeconds,mobileCrop:{width:W,height:H,aspectRatio:Number((W/H).toFixed(4)),position:"center"},focalPosition:null,candidateCount:sampled.selection.candidateCount,viableCandidateCount:sampled.frames.length,selectionMethod:"two-stage-mobile-crop-aware-v1",mobileCropScore:chosen,sourceType:"prepared-video-frame",batch:"c2-production-batch-100",preparedAt:new Date().toISOString()}; await writeFile(join(dir,"hero-video.json"),JSON.stringify(metadata,null,2)+"\n"); records.push({batchIndex:row.batchIndex,identity,status:"created",sourceVideo:row.vdjPath,heroPath:join(dir,"hero-video.jpg"),selectedSeconds,candidateCount:sampled.selection.candidateCount,viableCandidateCount:sampled.frames.length,mobileCrop:metadata.mobileCrop}); console.log(`[${i+1}/100] ${row.artist} — ${row.title} · ${identity}`); }
 await writeFile(join(root,"hero-manifest.json"),JSON.stringify({version:1,generatedAt:new Date().toISOString(),runtimeMs:Date.now()-started,scope:"exact-100-selection",mobileCrop:{width:W,height:H,position:"center"},focalPositionImplemented:false,records},null,2)+"\n"); console.log(JSON.stringify({total:records.length,created:records.filter(r=>r.status==="created").length,reused:records.filter(r=>r.status==="reused").length,failed:records.filter(r=>r.status==="failed").length},null,2)); }
main().catch(e=>{console.error(e);process.exitCode=1});
