import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadEnvFiles } from "../live/shared";

const root = join(process.cwd(), "reports/c2-terra-production-100");
const clean = (x: any) => String(typeof x === "string" ? x : x?.fact ?? x?.claim ?? x?.text ?? JSON.stringify(x)).split(/(?<=[.!?])\s+/).filter((s: string) => !/file|filename|owned video|asset|VDJ|VirtualDJ|metadata|Bob|Retroverse|RVTR|Collector|Editor|database|canonical|research packet|provenance|catalog|library|media-file|media entry/i.test(s)).join(" ").trim();
const wc = (s: string) => s.trim().split(/\s+/).filter(Boolean).length;
const forbidden = /\b(file|filename|owned video|asset|VDJ|VirtualDJ|metadata|Bob|Retroverse|RVTR|Collector|Editor|database|canonical|research packet|provenance|Chart Journey exists)\b/i;
const puff = /more than just|not just.{0,30}but|stands as a testament|cemented its place|continues to resonate|enduring appeal|timeless|iconic|cultural phenomenon|would go on to|little did they know|in many ways|remains a beloved|captured the hearts|left an indelible mark|transcends generations/i;
async function json(p: string) { return JSON.parse(await readFile(p, "utf8")); }
async function main() {
  await mkdir(root, { recursive: true }); loadEnvFiles(process.cwd()); if (!process.env.OPENAI_API_KEY?.trim()) throw new Error("OPENAI_API_KEY unavailable after normal project environment loading");
  const queue = await json(join(process.cwd(), "reports/c2-overnight-preparation-500/editor-ready-queue.json")); const prior = await json(join(process.cwd(), "reports/c2-terra-editor-proof-25/terra-editor-manifest.json")); const excluded = new Set(prior.results.map((r: any) => r.subject));
  const selected = queue.records.filter((r: any) => !excluded.has(r.editorialSubject)).slice(0, 100); if (selected.length !== 100) throw new Error(`Expected 100, found ${selected.length}`);
  const progressPath = join(root, "progress.json"); const old = await readFile(progressPath, "utf8").then(JSON.parse).catch(() => ({ results: [] })); const done = new Map((old.results ?? []).map((r: any) => [r.vdjPath, r]));
  const handoffs: any[] = []; for (const r of selected) { const d = await json(join(process.cwd(), r.collectorPath)); const facts = Array.isArray(d.candidateFacts) ? d.candidateFacts : []; handoffs.push({ subject: r.editorialSubject, angle: clean(d.storySeed?.[0] ?? d.summary ?? `The interesting thing here is the specific story of ${r.editorialSubject}.`), verifiedFacts: facts.slice(0, 12).map(clean).filter((x: string) => x.length > 12), chartFacts: d.charts?.summary && !/no chart/i.test(d.charts.summary) ? [clean(d.charts.summary)] : [], context: [clean(d.videoPerformance?.summary), clean(d.culturalContext?.summary)].filter((x: string) => x.length > 12), doNotClaim: (d.missingAreas ?? []).map(clean), vdjPath: r.vdjPath, rvtr: r.rvtr, canonicalStatus: r.rvtr && !String(r.rvtr).startsWith("VDJ-") ? "canonical-linked" : "VDJ-only", chartJourney: Boolean(r.charts?.peakHot100) }); }
  await writeFile(join(root, "selection-report.md"), `# Terra Production Editorial Batch — 100\n\nExactly 100 existing EDITOR_READY subjects selected in backlog order, excluding the 25 Terra proof subjects.\n\n- Canonical-linked: ${handoffs.filter(r => r.canonicalStatus === "canonical-linked").length}\n- VDJ-only: ${handoffs.filter(r => r.canonicalStatus === "VDJ-only").length}\n- Chart Journey available: ${handoffs.filter(r => r.chartJourney).length}\n`);
  await writeFile(join(root, "editor-handoffs.json"), JSON.stringify({ version: 1, model: "gpt-5.6-terra", records: handoffs.map(({ vdjPath, ...h }) => h) }, null, 2) + "\n");
  const model = "gpt-5.6-terra"; const results: any[] = [...done.values()];
  for (const [i, h] of handoffs.entries()) { if (done.has(h.vdjPath)) continue; const prompt = `Write a 150–250 word short music/culture magazine article about SUBJECT. Use ONLY the clean handoff facts. Do not use model memory. Choose one clear angle and write a specific headline. Do not mention internal systems or the handoff. Avoid generic significance conclusions and AI puff language. Return JSON only: {"headline":"...","article":"..."}.\n\nCLEAN HANDOFF:\n${JSON.stringify({ subject: h.subject, angle: h.angle, verifiedFacts: h.verifiedFacts, chartFacts: h.chartFacts, context: h.context, doNotClaim: h.doNotClaim })}`; const started = Date.now(); let status = "API_FAILED", article: any = {}, inputTokens = 0, outputTokens = 0, error = null;
    try { const response = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ model, response_format: { type: "json_object" }, messages: [{ role: "system", content: "You are a careful music journalist. Output valid JSON only." }, { role: "user", content: prompt }] }) }); const j = await response.json(); if (!response.ok) throw new Error(j.error?.message ?? `OpenAI ${response.status}`); inputTokens = j.usage?.prompt_tokens ?? 0; outputTokens = j.usage?.completion_tokens ?? 0; try { article = JSON.parse(j.choices?.[0]?.message?.content ?? "{}"); } catch {} const issues: string[] = []; const n = wc(String(article.article ?? "")); if (n < 150 || n > 250) issues.push("word-count"); if (forbidden.test(`${article.headline} ${article.article}`)) issues.push("internal-leakage"); if (puff.test(`${article.headline} ${article.article}`)) issues.push("ai-puff-language"); if (!article.headline || !article.article) issues.push("weak-output"); status = issues.length ? "TERRA_REVIEW_REQUIRED" : "TERRA_FIRST_PASS"; results.push({ batchIndex: i + 1, vdjPath: h.vdjPath, subject: h.subject, headline: article.headline ?? "", article: article.article ?? "", status, qualityIssues: issues, wordCount: n, latencyMs: Date.now() - started, inputTokens, outputTokens, canonicalStatus: h.canonicalStatus, chartJourney: h.chartJourney, rvtr: h.rvtr }); } catch (e) { error = String(e); results.push({ batchIndex: i + 1, vdjPath: h.vdjPath, subject: h.subject, status, qualityIssues: ["api-failed"], error, latencyMs: Date.now() - started, inputTokens, outputTokens, canonicalStatus: h.canonicalStatus, chartJourney: h.chartJourney, rvtr: h.rvtr }); }
    await writeFile(progressPath, JSON.stringify({ version: 1, updatedAt: new Date().toISOString(), results }, null, 2) + "\n"); console.log(`[${i + 1}/100] ${h.subject} ${status}`); if (results.length === 20 && results.filter(r => r.status === "TERRA_FIRST_PASS").length < 18) { console.log("STOP after first-20 checkpoint"); break; } }
  const final = { version: 1, model, generatedAt: new Date().toISOString(), selected: selected.length, results }; await writeFile(join(root, "terra-editor-manifest.json"), JSON.stringify(final, null, 2) + "\n"); console.log(JSON.stringify({ generated: results.length, passes: results.filter(r => r.status === "TERRA_FIRST_PASS").length, review: results.filter(r => r.status === "TERRA_REVIEW_REQUIRED").length, apiFailed: results.filter(r => r.status === "API_FAILED").length }, null, 2));
}
main().catch(e => { console.error(e); process.exitCode = 1; });
