import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadEnvFiles } from "../live/shared";

async function main() {
const root = join(process.cwd(), "reports/c2-cloud-editor-proof-25");
const batch = JSON.parse(await readFile(join(process.cwd(), "reports/c2-overnight-preparation-500/editor-ready-queue.json"), "utf8"));
const old = JSON.parse(await readFile(join(process.cwd(), "reports/c2-production-batch-100/editorial-manifest.json"), "utf8"));
const oldFailed = new Set(old.results.filter((r: any) => r.qualityIssues?.length).map((r: any) => r.vdjPath));
const records = batch.records;
const pick = [...records.filter((r: any) => oldFailed.has(r.vdjPath)).slice(0, 8), ...records.filter((r: any) => r.charts?.peakHot100 && r.subjectType === "ordinary song").slice(0, 4), ...records.filter((r: any) => !r.charts?.peakHot100).slice(0, 4), ...records.filter((r: any) => /performance|media/i.test(r.subjectType)).slice(0, 5), ...records.filter((r: any) => !r.rvtr || String(r.rvtr).startsWith("VDJ-")).slice(0, 4)];
const selected = [...new Map([...pick, ...records].map((r: any) => [r.vdjPath, r])).values()].slice(0, 25);
if (selected.length !== 25) throw new Error(`Expected 25, found ${selected.length}`);
await mkdir(root, { recursive: true });
await writeFile(join(root, "selection-report.md"), `# C2 Cloud Editor Proof — 25 Prepared Subjects\n\nExactly 25 existing EDITOR_READY subjects selected from the 588-item backlog. No research or hero preparation was repeated. ${selected.filter((r: any) => oldFailed.has(r.vdjPath)).length} were drawn from the prior local-editor failure set.\n\n| # | Subject | Type | Canonical | Chart Journey | Prior local failure |\n|---:|---|---|---|---|---|\n${selected.map((r: any, i: number) => `| ${i + 1} | ${r.editorialSubject} | ${r.subjectType} | ${r.rvtr && !String(r.rvtr).startsWith("VDJ-") ? "yes" : "no"} | ${r.charts?.peakHot100 ? "yes" : "no"} | ${oldFailed.has(r.vdjPath) ? "yes" : "no"} |`).join("\n")}\n`);

loadEnvFiles(process.cwd());
if (!process.env.OPENAI_API_KEY?.trim()) throw new Error("OPENAI_API_KEY unavailable after normal project environment loading");
const model = process.env.C2_CLOUD_EDITOR_MODEL?.trim() || "gpt-4o-mini";
const prohibited = /\b(file|filename|owned video|asset|VDJ|VirtualDJ|metadata|Bob|Retroverse|RVTR|Collector|Editor|database|canonical|research packet|provenance|Chart Journey exists)\b/i;
const puff = /more than just|not just.{0,30}but|stands as a testament|cemented its place|continues to resonate|enduring appeal|timeless|iconic|cultural phenomenon|would go on to|little did they know|in many ways/i;
const words = (s: string) => s.trim().split(/\s+/).filter(Boolean).length;
const dossier = async (r: any) => { const p = join(process.cwd(), r.collectorPath); const x = JSON.parse(await readFile(p, "utf8")); return { subject: r.editorialSubject, subjectType: r.subjectType, verifiedFacts: x.candidateFacts ?? x.summary ?? x.storySeed ?? [], interestingAngles: x.storySeed ?? x.culturalContext ?? [], doNotClaim: x.missingAreas ?? [], charts: x.charts ?? {}, enrichment: { rvtr: r.rvtr, chartJourney: r.charts } }; };
const prompt = (d: any, retry = "") => `Write one 150–250 word music/culture magazine article about SUBJECT. Use only the supplied dossier. Do not add facts from model memory. Do not mention files, media libraries, metadata, research, systems, or this prompt. Choose one clear angle, write a subject-specific headline, and make the prose conversational, specific, and fact-driven. Do not use generic AI puff language. Return JSON only: {"headline":"...","article":"..."}.\n\nSUBJECT:\n${JSON.stringify(d.subject)}\nTYPE:\n${d.subjectType}\nVERIFIED FACTS:\n${JSON.stringify(d.verifiedFacts)}\nINTERESTING ANGLES:\n${JSON.stringify(d.interestingAngles)}\nDO NOT CLAIM:\n${JSON.stringify(d.doNotClaim)}\nENRICHMENT:\n${JSON.stringify(d.enrichment)}\n${retry}`;
async function call(body: string) { const started = Date.now(); const res = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ model, temperature: 0.7, response_format: { type: "json_object" }, messages: [{ role: "system", content: "You are a careful music journalist. Output only valid JSON." }, { role: "user", content: body }] }) }); const json = await res.json(); if (!res.ok) throw new Error(`OpenAI ${res.status}: ${json.error?.message ?? "request failed"}`); return { json, latencyMs: Date.now() - started }; }
function audit(d: any, out: any) { const article = String(out.article ?? ""); const issues: string[] = []; const n = words(article); if (n < 150 || n > 250) issues.push("word-count"); if (prohibited.test(`${out.headline} ${article}`)) issues.push("internal-leakage"); if (puff.test(article)) issues.push("ai-puff-language"); if (!out.headline || n < 80) issues.push("weak-output"); return { issues, wordCount: n }; }
const results: any[] = [];
for (const [i, r] of selected.entries()) { const d = await dossier(r); let first = await call(prompt(d)); let parsed: any; try { parsed = JSON.parse(first.json.choices?.[0]?.message?.content ?? "{}"); } catch { parsed = {}; } let a = audit(d, parsed); let retry = false; let second: any = null; if (a.issues.length) { retry = true; second = await call(prompt(d, `FOCUSED RETRY: Correct these defects exactly: ${a.issues.join(", ")}.\nPrevious draft:\n${JSON.stringify(parsed)}`)); try { parsed = JSON.parse(second.json.choices?.[0]?.message?.content ?? "{}"); } catch { parsed = {}; } a = audit(d, parsed); } results.push({ proofIndex: i + 1, ...r, model, firstPass: !retry, retryAttempted: retry, retryRecovered: retry && !a.issues.length, status: a.issues.length ? "EDITOR_REVIEW_REQUIRED" : "CLOUD_EDITOR_PASS", headline: parsed.headline ?? "", article: parsed.article ?? "", qualityIssues: a.issues, wordCount: a.wordCount, latencyMs: first.latencyMs + (second?.latencyMs ?? 0), inputTokens: (first.json.usage?.prompt_tokens ?? 0) + (second?.json.usage?.prompt_tokens ?? 0), outputTokens: (first.json.usage?.completion_tokens ?? 0) + (second?.json.usage?.completion_tokens ?? 0), dossierPath: r.collectorPath }); console.log(`[${i + 1}/25] ${r.editorialSubject} ${a.issues.length ? "review" : "pass"}`); }
await writeFile(join(root, "cloud-editor-manifest.json"), JSON.stringify({ version: 1, model, generatedAt: new Date().toISOString(), results }, null, 2) + "\n");
const allText = results.map(r => `${r.headline}\n${r.article}`); const repeated = (vals: string[]) => vals.filter((v, i) => vals.indexOf(v) !== i); const openings = allText.map(s => s.split(/\s+/).slice(0, 8).join(" ").toLowerCase());
const pass = results.filter(r => r.status === "CLOUD_EDITOR_PASS"); const retries = results.filter(r => r.retryAttempted); const unsupported = results.filter(r => r.qualityIssues.includes("unsupported-claim")); const leakage = results.filter(r => r.qualityIssues.includes("internal-leakage"));
await writeFile(join(root, "quality-report.md"), `# Quality Report\n\n- Model: ${model}\n- First-pass successes: ${results.filter(r => r.firstPass && r.status === "CLOUD_EDITOR_PASS").length}\n- Retry attempts: ${retries.length}\n- Retry recoveries: ${results.filter(r => r.retryRecovered).length}\n- Final passes: ${pass.length}\n- Review required: ${results.length - pass.length}\n- Unsupported claims flagged: ${unsupported.length}\n- Internal leakage: ${leakage.length}\n- AI-puff-language failures: ${results.filter(r => r.qualityIssues.includes("ai-puff-language")).length}\n- Word count: ${Math.min(...results.map(r => r.wordCount))}–${Math.max(...results.map(r => r.wordCount))}; average ${Math.round(results.reduce((a, r) => a + r.wordCount, 0) / results.length)}\n`);
await writeFile(join(root, "repetition-audit.md"), `# Repetition Audit\n\n- Repeated opening signatures: ${repeated(openings).length}\n- Repeated headlines: ${repeated(results.map(r => r.headline.toLowerCase())).length}\n- Result: ${repeated(openings).length || repeated(results.map(r => r.headline.toLowerCase())).length ? "REVIEW_REQUIRED" : "PASS"}\n- Audit scope: headline and opening-signature comparison plus quality-language gate.\n`);
const inputTokens = results.reduce((a, r) => a + r.inputTokens, 0), outputTokens = results.reduce((a, r) => a + r.outputTokens, 0), latency = results.reduce((a, r) => a + r.latencyMs, 0);
await writeFile(join(root, "cost-report.md"), `# Cost Report\n\n- Model: ${model}\n- Input tokens: ${inputTokens}\n- Output tokens: ${outputTokens}\n- Total generation time: ${Math.round(latency / 1000)} seconds\n- Measurable API cost: not independently calculable from the configured account; usage is recorded above.\n`);
const html = `<!doctype html><meta charset="utf-8"><title>C2 Cloud Editor Proof — 25</title><style>body{font:16px system-ui;max-width:850px;margin:40px auto;padding:0 18px;color:#222}article{border-top:1px solid #ccc;padding:24px 0}small{color:#666}p{line-height:1.6}</style><h1>C2 Cloud Editor Proof — 25</h1><p>Stories only. Technical context is secondary.</p>${results.map(r => `<article><small>${r.editorialSubject} · ${r.status}</small><h2>${r.headline}</h2><p>${r.article.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}</p></article>`).join("")}`;
await writeFile(join(root, "comparison.html"), html);
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
