require("../finance/preload-server-only.cjs");
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = join(process.cwd(), "reports/c2-production-batch-100");
const model = process.env.INTELLIGENCE_OLLAMA_MODEL?.trim() || "qwen3:8b";
const base = process.env.OLLAMA_HOST?.trim() || "http://127.0.0.1:11434";
const leak = /\b(file|filename|owned video|video asset|asset|VDJ|VirtualDJ|metadata|Retroverse|RVTR|Collector|Editor|database|canonical|provenance|research packet|Chart Journey exists)\b/i;
const generic = /the story behind|why .* still matters|an enduring classic|inside .*|how .* changed everything/i;
function words(s: string) { return s.trim().split(/\s+/).filter(Boolean).length; }
async function generate(prompt: string, modelName = model) { const t = Date.now(); const res = await fetch(`${base}/api/generate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ model: modelName, prompt, stream: false, think: false, options: { temperature: 0.35, num_predict: 900 } }), signal: AbortSignal.timeout(180000) }); if (!res.ok) throw new Error(`ollama ${res.status}`); const data: any = await res.json(); return { text: String(data.response ?? "").replace(/[\s\S]*?<\/think>/i, "").trim(), runtimeMs: Date.now() - t }; }
function packetPrompt(row: any, pkg: any) { const facts = [...(pkg.candidateFacts ?? []), ...(pkg.recording?.notes ?? []).map((text: string) => ({ text, confidence: 0.8 })), ...(pkg.culturalContext?.notes ?? []).map((text: string) => ({ text, confidence: 0.8 }))].filter((f: any) => f.text && f.confidence >= 0.75).slice(0, 14).map((f: any) => `- ${f.text}`).join("\n"); return `You are a careful music-magazine editor. Write a subject-first article using ONLY the verified facts below. Do not add facts from memory. Subject: ${pkg.artist} — ${pkg.title}. VDJ context is only a clue and must not appear in prose. Trusted enrichment: ${pkg.charts?.peakHot100 != null ? `Hot 100 peak #${pkg.charts.peakHot100}; ${pkg.charts.chartWeeks ?? "unknown"} weeks.` : "No verified chart data."} ${pkg.identity?.year ? `Year: ${pkg.identity.year}.` : ""} Verified facts:\n${facts || "- No sufficiently strong facts; write a short, cautious listening-focused piece without historical claims."}\nReturn JSON with headline and article. Article must be 150–250 words, specific, conversational, and never mention files, metadata, systems, research, or provenance. Avoid generic headlines.`; }
function check(text: string, row: any) { const issues: string[] = []; if (words(text) < 150 || words(text) > 250) issues.push("word-count"); if (leak.test(text)) issues.push("internal-leakage"); if (generic.test(text)) issues.push("generic-headline-or-copy"); if (!text.toLowerCase().includes(String(row.title).toLowerCase().split(/\s+/)[0])) issues.push("subject-confusion"); if (/in conclusion|timeless|ever-evolving|testament to|resonates with audiences/i.test(text)) issues.push("generic-puff"); return issues; }
async function main() { const selection = JSON.parse(await readFile(join(root, "selection-manifest.json"), "utf8")); const research = JSON.parse(await readFile(join(root, "research-manifest.json"), "utf8")); const prior = await readFile(join(root, "editorial-progress.json"), "utf8").then(JSON.parse).catch(() => ({ results: [] })); const out: any[] = [...(prior.results ?? [])]; const byPath = new Map(research.results.map((r: any) => [r.vdjPath, r])); const comparison: any[] = [];
  for (const row of selection.records) { if (out.some(r => r.vdjPath === row.vdjPath)) continue; const rr: any = byPath.get(row.vdjPath); let pkg: any = null; try { pkg = JSON.parse(await readFile(join(process.cwd(), rr.collectorPath), "utf8")); } catch {}
    const prompt = packetPrompt(row, pkg ?? { artist: row.artist, title: row.title }); let attempt1: any = null; let retry: any = null; let issues: string[] = []; try { attempt1 = await generate(prompt); issues = check(attempt1.text, row); } catch (e) { issues = [String(e)]; }
    if (issues.length) { const retryPrompt = `${prompt}\n\nFocused quality feedback: ${issues.join(", ")}. Retry once. Correct only these issues and return the same JSON shape.`; try { retry = await generate(retryPrompt); const retryIssues = check(retry.text, row); if (retryIssues.length) issues = retryIssues; else issues = []; } catch (e) { issues = [String(e)]; } }
    const final = retry && !issues.length ? retry : attempt1; const parsed = (() => { try { const c = String(final?.text ?? "").replace(/```json|```/g, ""); const a = c.indexOf("{"); const b = c.lastIndexOf("}"); return a >= 0 ? JSON.parse(c.slice(a, b + 1)) : { headline: row.title, article: c }; } catch { return { headline: row.title, article: String(final?.text ?? "") }; } })();
    out.push({ batchIndex: row.batchIndex, vdjPath: row.vdjPath, rvtr: rr?.rvtr ?? row.rvtr, artist: row.artist, title: row.title, subject: `${row.artist} — ${row.title}`, verifiedSourceCount: rr?.sourceCount ?? 0, researchQuality: rr?.researchQuality ?? null, model, ollamaAttempt1: { status: attempt1 ? (issues.length && !retry ? "failed" : "pass-or-retried") : "failed", runtimeMs: attempt1?.runtimeMs ?? null, issues: issues.length && !retry ? issues : [] }, ollamaRetry: retry ? { status: issues.length ? "failed" : "pass", runtimeMs: retry.runtimeMs, issues: issues.length ? issues : [] } : { status: "not-needed" }, cloudFallback: false, cloudEscalationReason: null, headline: parsed.headline ?? row.title, article: parsed.article ?? "", wordCount: words(parsed.article ?? ""), qualityIssues: issues, humanReview: Boolean(issues.length || !pkg || (rr?.researchQuality ?? 0) < 40), chartJourney: row.chartJourneyStatus === "AVAILABLE", relatedMusicStrategy: row.chartJourneyStatus === "AVAILABLE" ? "chart-fingerprint" : "owned-video-context" });
    if (row.batchIndex <= 3) comparison.push({ batchIndex: row.batchIndex, subject: `${row.artist} — ${row.title}`, model, runtimeMs: attempt1?.runtimeMs ?? null, wordCount: words(parsed.article ?? ""), issues }); console.log(`[${row.batchIndex}/100] ${row.artist} — ${row.title} · ${issues.length ? "review" : "pass"}`);
    await writeFile(join(root, "editorial-progress.json"), JSON.stringify({ version: 1, model, updatedAt: new Date().toISOString(), results: out }, null, 2) + "\n");
  }
  await writeFile(join(root, "editorial-manifest.json"), JSON.stringify({ version: 1, model, generatedAt: new Date().toISOString(), results: out }, null, 2) + "\n"); await writeFile(join(root, "model-comparison.json"), JSON.stringify({ modelsCompared: [model], comparison, note: "The configured qwen3:8b was used; qwen3-vl:4b is vision-oriented and was not used for text." }, null, 2) + "\n"); console.log(JSON.stringify({ total: out.length, pass: out.filter(r => !r.qualityIssues.length).length, retryPass: out.filter(r => r.ollamaRetry.status === "pass").length, failures: out.filter(r => r.qualityIssues.length).length, humanReview: out.filter(r => r.humanReview).length }, null, 2)); }
main().catch(e => { console.error(e); process.exitCode = 1; });
