import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadEnvFiles } from "../live/shared";

const root=join(process.cwd(),"reports/c2-terra-backlog-completion"); const model="gpt-5.6-terra";
const forbidden=/\b(file|filename|owned video|asset|VDJ|VirtualDJ|metadata|Bob|Retroverse|RVTR|Collector|Editor|database|canonical|research packet|provenance|Chart Journey exists)\b/i; const puff=/more than just|not just.{0,30}but|stands as a testament|cemented its place|continues to resonate|enduring appeal|timeless|iconic|cultural phenomenon|would go on to|little did they know|in many ways|remains a beloved|captured the hearts|left an indelible mark|transcends generations/i; const wc=(s:string)=>s.trim().split(/\s+/).filter(Boolean).length;
const clean=(x:any)=>String(typeof x==='string'?x:x?.fact??x?.claim??x?.text??JSON.stringify(x)).split(/(?<=[.!?])\s+/).filter((s:string)=>!/file|filename|owned video|asset|VDJ|VirtualDJ|metadata|Bob|Retroverse|RVTR|Collector|Editor|database|canonical|research packet|provenance|catalog|library|media-file|media entry/i.test(s)).join(' ').trim();
async function j(p:string){return JSON.parse(await readFile(p,'utf8'))} async function save(p:string,x:any){await writeFile(p,JSON.stringify(x,null,2)+'\n')}
function audit(a:any){const issues:string[]=[];const n=wc(String(a.article??''));if(n<150||n>250)issues.push('word-count');if(forbidden.test(`${a.headline} ${a.article}`))issues.push('internal-leakage');if(puff.test(`${a.headline} ${a.article}`))issues.push('ai-puff-language');if(!a.headline||!a.article)issues.push('weak-output');return {issues,wordCount:n}}
async function call(h:any, previous?:any, reason?:string){const prompt=`Write a 150–250 word short music/culture magazine article about SUBJECT. Use ONLY the clean handoff facts. Do not use model memory. Choose one clear angle and a specific headline. Do not mention internal systems or the handoff. Avoid generic significance conclusions and AI puff language. ${previous?`Repair ONLY these defects: ${reason}. Preserve factual discipline and angle. Previous article: ${JSON.stringify(previous)}`:''} Return JSON only: {"headline":"...","article":"..."}.\nCLEAN HANDOFF:\n${JSON.stringify({subject:h.subject,angle:h.angle,verifiedFacts:h.verifiedFacts,chartFacts:h.chartFacts,context:h.context,doNotClaim:h.doNotClaim})}`;const started=Date.now();const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,response_format:{type:'json_object'},messages:[{role:'system',content:'You are a careful music journalist. Output valid JSON only.'},{role:'user',content:prompt}]})});const z=await r.json();if(!r.ok)throw new Error(z.error?.message??`OpenAI ${r.status}`);let a:any={};try{a=JSON.parse(z.choices?.[0]?.message?.content??'{}')}catch{};return {...a,...audit(a),latencyMs:Date.now()-started,inputTokens:z.usage?.prompt_tokens??0,outputTokens:z.usage?.completion_tokens??0}}
async function main(){await mkdir(root,{recursive:true});loadEnvFiles(process.cwd());if(!process.env.OPENAI_API_KEY?.trim())throw new Error('OPENAI_API_KEY unavailable');const q=await j(join(process.cwd(),'reports/c2-overnight-preparation-500/editor-ready-queue.json'));const prod=await j(join(process.cwd(),'reports/c2-terra-production-100/terra-editor-manifest.json'));const prior25=await j(join(process.cwd(),'reports/c2-terra-editor-proof-25/terra-editor-manifest.json'));const failed=prod.results.filter((r:any)=>r.status!=='TERRA_FIRST_PASS');const all= q.records.filter((r:any)=>!new Set(prior25.results.map((x:any)=>x.subject)).has(r.editorialSubject));const handoffs:any[]=[];for(const r of all){const d=await j(join(process.cwd(),r.collectorPath));handoffs.push({subject:r.editorialSubject,angle:clean(d.storySeed?.[0]??d.summary??`The interesting thing here is the specific story of ${r.editorialSubject}.`),verifiedFacts:(d.candidateFacts??[]).slice(0,12).map(clean).filter((x:string)=>x.length>12),chartFacts:d.charts?.summary&&!/no chart/i.test(d.charts.summary)?[clean(d.charts.summary)]:[],context:[clean(d.videoPerformance?.summary),clean(d.culturalContext?.summary)].filter((x:string)=>x.length>12),doNotClaim:(d.missingAreas??[]).map(clean),subject:r.editorialSubject,rvtr:r.rvtr,canonicalStatus:r.rvtr&&!String(r.rvtr).startsWith('VDJ-')?'canonical-linked':'VDJ-only',chartJourney:Boolean(r.charts?.peakHot100),vdjPath:r.vdjPath})}
await writeFile(join(root,'selection-report.md'),`# Terra Backlog Completion\n\nPhase A: exactly 9 existing review-required articles. Phase B: ${handoffs.length-9} existing prepared subjects. No research or hero work repeated.\n`);await save(join(root,'editor-handoffs.json'),{model,records:handoffs.map(({vdjPath,...x})=>x)});
const pp=join(root,'progress.json');const old=await readFile(pp,'utf8').then(JSON.parse).catch(()=>({results:[]}));const done=new Map((old.results??[]).map((r:any)=>[r.vdjPath,r]));
const phaseA:any[]=[];for(const r of failed){const h=handoffs.find(x=>x.subject===r.subject);if(!h)continue;if(done.has(r.vdjPath))phaseA.push(done.get(r.vdjPath));else{try{const x=await call(h,{headline:r.headline,article:r.article},r.qualityIssues.join(', '));const y={vdjPath:r.vdjPath,subject:h.subject,phase:'A',firstStatus:r.status,repairAttempted:true,status:x.issues.length?'BOB_REVIEW_REQUIRED':'TERRA_FINAL',...x,rvtr:h.rvtr,canonicalStatus:h.canonicalStatus,chartJourney:h.chartJourney};phaseA.push(y);done.set(r.vdjPath,y)}catch(e){const y={vdjPath:r.vdjPath,subject:h.subject,phase:'A',status:'API_FAILED',error:String(e)};phaseA.push(y);done.set(r.vdjPath,y)}await save(pp,{updatedAt:new Date().toISOString(),results:[...done.values()]})}}
const passedA=phaseA.filter(r=>r.status==='TERRA_FINAL').length;if(passedA<8){await save(join(root,'repair-manifest.json'),{results:phaseA});console.log(JSON.stringify({phaseA:phaseA.length,passedA,stopped:true}));return}
for(const h of handoffs.filter(h=>!failed.some((r:any)=>r.subject===h.subject))){if(done.has(h.vdjPath))continue;let y:any;try{const x=await call(h);y={vdjPath:h.vdjPath,subject:h.subject,phase:'B',firstStatus:x.issues.length?'TERRA_REPAIR_REQUIRED':'TERRA_FIRST_PASS',repairAttempted:false,status:x.issues.length?'TERRA_REPAIR_REQUIRED':'TERRA_FINAL',...x,rvtr:h.rvtr,canonicalStatus:h.canonicalStatus,chartJourney:h.chartJourney};if(x.issues.length){const z=await call(h,x,x.issues.join(', '));y={...y,repairAttempted:true,repairStatus:z.issues.length?'BOB_REVIEW_REQUIRED':'TERRA_FINAL',status:z.issues.length?'BOB_REVIEW_REQUIRED':'TERRA_FINAL',headline:z.headline,article:z.article,qualityIssues:z.issues,wordCount:z.wordCount,latencyMs:y.latencyMs+z.latencyMs,inputTokens:y.inputTokens+z.inputTokens,outputTokens:y.outputTokens+z.outputTokens}}}catch(e){y={vdjPath:h.vdjPath,subject:h.subject,phase:'B',status:'API_FAILED',error:String(e)}}done.set(h.vdjPath,y);await save(pp,{updatedAt:new Date().toISOString(),results:[...done.values()]});console.log(`${done.size}/${handoffs.length} ${h.subject} ${y.status}`)}
const results=[...done.values()];await save(join(root,'terra-final-manifest.json'),{model,results});await save(join(root,'repair-manifest.json'),{results:results.filter(r=>r.phase==='A')});await save(join(root,'bob-review-queue.json'),{results:results.filter(r=>r.status==='BOB_REVIEW_REQUIRED')});console.log(JSON.stringify({phaseA:phaseA.length,passedA,phaseB:results.filter(r=>r.phase==='B').length,final:results.filter(r=>r.status==='TERRA_FINAL').length,review:results.filter(r=>r.status==='BOB_REVIEW_REQUIRED').length,apiFailed:results.filter(r=>r.status==='API_FAILED').length},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1})
