import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = process.cwd();
const OUT = join(ROOT, "reports/editorial-song-diversity-25");
const INVENTORY = join(ROOT, "reports/vdj-library-coverage/inventory.json");
const PACKAGE_ROOT = join(ROOT, "..", "RETROVERSE_DATA/ops/intelligence/packages");

type Seed = { headline: string; lede: string; middle: string; close: string; sources?: string[] };
type Row = Record<string, any>;

const IDS = [
  "RVTR160225", "RVTR952686", "RVTR979650", "RVTR223139", "RVTR251858", "RVTR025701", "RVTR604727",
  "RVTR347287", "RVTR572817", "RVTR086340", "RVTR521270", "RVTR285085", "RVTR417030", "RVTR792762",
  "RVTR478078", "RVTR435218", "RVTR472172", "RVTR143275", "RVTR269180", "RVTR528167", "RVTR353865",
  "RVTR669909", "RVTR311683", "RVTR273312", "RVTR013681",
];

const SEEDS: Record<string, Seed> = {
  RVTR160225: { headline: "A blues standard with a life of its own", lede: "Cab Calloway’s “St. James Infirmary Blues” belongs to the oldest kind of popular song: one whose author keeps receding while the performance keeps taking new shapes.", middle: "Calloway’s version carries the theatrical authority of a bandleader who understood that a blues number could be a scene, not just a chord progression. The voice, the brass, and the deliberate pacing make the song feel staged in the best sense — a compact drama with a narrator who knows the room is listening.", close: "Its place in the collection is less about a chart peak than about transmission. This is a recording that survives because each performer can leave a different shadow across the same old doorway." },
  RVTR952686: { headline: "The laugh inside the rock-and-roll shout", lede: "“Chantilly Lace” is built on a phone call, but the joke only works because the Big Bopper makes the telephone feel like a stage prop.", middle: "Jiles Perry Richardson turns flirtation into a piece of comic timing: the spoken asides, the exaggerated confidence, and the sudden return to the hook. The record is part novelty, part rockabilly performance, and completely aware that personality can be the main instrument.", close: "That theatrical directness explains why the song still feels immediate. It does not ask the listener to decode a mood; it opens the line, turns up the character, and lets the voice do the entertaining." },
  RVTR979650: { headline: "The guitar lesson that became a time machine", lede: "Chuck Berry wrote “Johnny B. Goode” as a rock-and-roll origin story, then later generations kept using it as shorthand for the moment a guitar changes the room.", middle: "The song’s fictional country boy carries pieces of Berry’s own life, but the record is bigger than biography. Its riff, forward motion, and plainspoken ambition turn a local dream into a universal scene: someone hears a player and realizes the future has arrived early.", close: "That is why the song travels so easily between a 1958 jukebox, a movie dance floor, and a spacecraft archive. The performance is rooted in one place while its idea of possibility keeps moving." , sources:["https://time.com/4707769/chuck-berry-johnny-b-goode/"]},
  RVTR223139: { headline: "When a B-side refused to stay in the margins", lede: "Conway Twitty’s “It’s Only Make Believe” was first issued as the other side of a single, but the vocal made it impossible to treat as an afterthought.", middle: "Twitty leans into the song’s ache instead of sanding it down. The growl gives the melody a physical weight, and the performance sits at the crossroads of early rock, pop balladry, and the country voice he would later make famous.", close: "The record’s surprise is not that it became a hit; it is that the supposedly secondary track revealed the artist’s most persuasive feature. A side can become the center when the singer finds the truth in it." , sources:["https://conwaytwitty.com/about","https://www.officialcharts.com/songs/conway-twitty-its-only-make-believe/"]},
  RVTR251858: { headline: "The song that put a pair of boots in charge", lede: "Nancy Sinatra did not merely record “These Boots Are Made for Walkin’.” She changed who was allowed to sound dangerous inside a pop song.", middle: "Lee Hazlewood wrote the track for himself, but Sinatra heard the imbalance in the lyric and redirected it. Her low, playful delivery turns the threat into a boundary being drawn in real time, with Billy Strange’s arrangement and the Wrecking Crew giving the walk its unmistakable stride.", close: "The result is both fashion and argument: go-go boots, a contralto, and a rhythm section moving forward without asking permission. The record’s iconography works because the voice is already in control." , sources:["https://www.nancysinatra.com/about"]},
  RVTR025701: { headline: "A swamp story with a pop-song engine", lede: "Tony Joe White made “Polk Salad Annie” sound like a front-porch tale that had wandered into a studio built for television.", middle: "The groove is the key. White’s guitar and drawl keep the song earthy, while the arrangement gives the narrative enough lift to travel far beyond its setting. Annie is introduced through details, not explanation; the listener learns the world by hearing how the singer inhabits it.", close: "That balance between regional texture and pop momentum is why the record feels larger than its plot. It is a character sketch with a beat strong enough to carry the whole landscape." },
  RVTR604727: { headline: "The Bee Gees before the disco mirror", lede: "“To Love Somebody” catches the Bee Gees at a moment when harmony is still the architecture and pain is the weather moving through it.", middle: "Barry and Robin Gibb’s voices do not simply stack; they pull against one another. The gospel shape gives the song lift, while the restrained production leaves space for the plea to sound personal rather than ornamental.", close: "Long before the group’s later reinvention, this recording showed that their gift was not a genre but an emotional geometry: three voices finding pressure points inside a melody." },
  RVTR347287: { headline: "The night a memory learned to sing", lede: "Bob Seger’s “Night Moves” is a coming-of-age song that refuses to turn memory into a photograph. It keeps the headlights moving.", middle: "The lyric is full of specific summer details, but the arrangement keeps widening the frame. Acoustic movement, electric lift, and Seger’s weathered voice make youth feel less like a lost paradise than a place the narrator can still drive through.", close: "That is the song’s emotional intelligence. It remembers the heat and the awkwardness together, so the past arrives with its own grain instead of a clean nostalgic filter." },
  RVTR572817: { headline: "A bass line that made danger dance", lede: "Aerosmith’s “Sweet Emotion” begins with studio texture before it becomes a song, letting the bass and effects announce a world that is already humming.", middle: "The record’s power comes from contrast: a groove that feels almost relaxed, a vocal that carries suspicion, and a chorus that opens the doors without resolving the tension. The band sounds polished enough for radio but never fully domesticated by it.", close: "That mixture made the track a durable entrance point into Aerosmith’s seventies sound. The hook is memorable, but the atmosphere is what keeps pulling listeners back." },
  RVTR086340: { headline: "The club band that found a wider street", lede: "Dire Straits’ “Sultans of Swing” turns an ordinary night in a small club into an argument for paying attention to players who are not trying to be famous.", middle: "Mark Knopfler’s guitar is conversational rather than showy, and the rhythm section gives it room to describe the scene. The song’s restraint is its confidence: the band does not need a grand plot when the details already carry the music.", close: "The recording became a hit without surrendering that modest scale. Its world stays local, even as the guitar travels everywhere." },
  RVTR521270: { headline: "A Dutch pop record with a grin on its face", lede: "Mouth & MacNeal’s “How Do You Do” arrives as bright, communal pop: a song whose first job is to make the room answer back.", middle: "The performance uses the contrast between the two voices as its engine. It is playful without being weightless, built from the kind of direct melodic exchange that can cross language and market boundaries before anyone has time to overthink it.", close: "With no usable Chart Journey in the public packet, the song asks to be met through character and movement instead. Its story is the lift in the room — a small record with an unusually social pulse." },
  RVTR285085: { headline: "A world tour hidden inside a pop chorus", lede: "Paul Simon’s “You Can Call Me Al” is a travel song with a comic sense of scale: global percussion, a restless bass line, and a chorus that keeps the traveler human.", middle: "The Graceland-era production lets South African musical collaboration reshape the center of the record rather than decorate it. Simon’s lyrics remain curious and self-mocking, while the groove makes the song feel physically larger than the narrator’s uncertainty.", close: "Its brightness is not simplicity. The song moves because it is willing to let different musical histories share the same road." },
  RVTR417030: { headline: "The drum fill that changed the room", lede: "Phil Collins’s “In the Air Tonight” is often remembered as a single dramatic entrance, but the silence before that entrance is doing just as much work.", middle: "The production makes absence feel architectural. Echo, space, and the guarded vocal keep the listener waiting inside a private scene until the drums arrive with almost cinematic force. The performance never explains the mystery; it builds a room around it.", close: "That patience is why the record remains so recognizable. The famous moment lands because everything before it has taught the listener to listen for a door opening." },
  RVTR792762: { headline: "A continent-sized chorus from four precise parts", lede: "Toto’s “Africa” sounds enormous, but its appeal comes from how carefully its many details are fitted together.", middle: "The percussion, keyboards, guitars, and stacked vocals create a polished studio landscape without turning the song cold. Its lyrical fantasy is broad, while the arrangement is exacting — every part earns the sense of motion.", close: "The chorus became a cultural object of its own, but the recording rewards a closer listen. Beneath the singalong is an unusually disciplined piece of studio pop." },
  RVTR478078: { headline: "A body trying to keep up with its own mind", lede: "Talking Heads’ “Once in a Lifetime” begins with a groove and quickly becomes an identity crisis delivered by a man who cannot stop moving.", middle: "David Byrne’s vocal is half sermon, half startled observation. The band builds a loop that feels both communal and alien, while the performance keeps asking how a person arrived inside a life that suddenly looks unfamiliar.", close: "The song’s video and stage language made the physicality unforgettable, but the underlying trick is musical: repetition turns confusion into something the whole audience can inhabit." },
  RVTR435218: { headline: "A question loud enough for a generation", lede: "“What’s Up?” became a giant singalong without losing the uncertainty inside its question.", middle: "Linda Perry’s writing moves from private frustration to communal release, and the band keeps the arrangement open enough for the voice to remain the event. The song does not pretend to have a tidy answer; it makes asking feel powerful.", close: "That directness helped it travel far beyond its original scene. The record’s reach comes from leaving the question intact." },
  RVTR472172: { headline: "The bluesy hook hiding in a college-radio hit", lede: "Spin Doctors’ “Two Princes” sounds effortless because the band built its pop appeal on a groove that already knew how to play live.", middle: "The vocal phrasing, guitar bounce, and conversational lyric make the song feel like a roomful of musicians finding the pocket together. Its charm is not polish alone; it is the sense that the record could keep going after the fade.", close: "That looseness became its signature. The song reached a huge audience without losing the friendly rough edge that made it feel discovered rather than manufactured." },
  RVTR143275: { headline: "The rap record that turned embarrassment into proof", lede: "Biz Markie’s “Just a Friend” is funny because the hurt is real, and the performance never asks the listener to choose between the two.", middle: "The beat gives the story room to unfold, while Biz’s singing turns the chorus into an instantly repeatable piece of disbelief. The record’s looseness is part of its craft: personality keeps interrupting the expected polish.", close: "What sounds like a joke on first contact becomes an anthem for anyone who has been told a story that does not add up. The laugh is the door; the recognition is what stays." },
  RVTR269180: { headline: "A family sound crossing the Texas border", lede: "Los Lonely Boys’ “Heaven” carries the warmth of a family band while letting its guitar speak in a language that belongs to several traditions at once.", middle: "The Garza brothers’ playing gives the song its lift, but the vocal stays close to the ground. Blues, rock, and Latin influences are not presented as a lesson; they are simply the family’s working vocabulary.", close: "That ease is the record’s invitation. It sounds personal without being private, as if a home sound has opened its doors to the radio." },
  RVTR528167: { headline: "Madonna turns the groove into a command", lede: "“Music” does not ask the dance floor for permission. Madonna’s voice arrives as an instruction, and the production builds a world that obeys it.", middle: "The song’s electronic pulse is spare enough to leave room for attitude, while the vocal keeps shifting between invitation and control. It is club music with a pop star’s sense of staging: every repeated phrase becomes another light turning on.", close: "The record’s strength is its economy. It does not need a large story when the groove itself is the scene." },
  RVTR353865: { headline: "The quiet disaster behind the loudest chorus", lede: "Nickelback’s “How You Remind Me” makes emotional conflict sound immediate by putting the accusation right at the center of the chorus.", middle: "The verses keep the details compressed, then the guitars widen the frame when the hook arrives. That contrast gives the record its radio force: private frustration becomes a line thousands of people can sing at once.", close: "Its durability comes from the directness. The song does not hide its argument inside metaphor; it lets the friction power the melody." },
  RVTR669909: { headline: "A classic song finding its second voice", lede: "Chris Stapleton’s “Tennessee Whiskey” is a modern hit built from an older country-soul lineage, and its power comes from how little it needs to prove.", middle: "The arrangement leaves room around the vocal, allowing the melody to carry both ache and gratitude. Stapleton does not treat the song as a museum piece; the phrasing makes it feel lived in, as though the old lyric has found a new address.", close: "Its journey is a reminder that rediscovery is not the same as repetition. A familiar song can become newly legible when the singer changes the temperature." },
  RVTR311683: { headline: "A line dance built for the phone camera", lede: "Blanco Brown’s “The Git Up” is part song, part invitation: its structure is designed to turn listening into participation.", middle: "The record draws from country, hip-hop, and a deliberately simple instructional impulse. Its hook does not merely describe a move; it gives a crowd a reason to make one together, which is why the song traveled so quickly through short-form video culture.", close: "The music is generous about its purpose. It leaves space for other people to finish the performance." },
  RVTR273312: { headline: "A held note with a whole band behind it", lede: "Alabama Shakes’ “Hold On” makes patience sound physical: Brittany Howard’s voice pushes upward while the band keeps the ground moving beneath her.", middle: "The recording draws on soul, rock, and gospel without reducing any of them to costume. Howard’s phrasing turns the title into both instruction and survival tactic, while the arrangement grows around her rather than competing for the spotlight.", close: "The song’s emotional force is concentrated, not oversized. It gives endurance a groove and lets the voice carry the rest." },
  RVTR013681: { headline: "The Applebee’s song that escaped the commercial", lede: "Walker Hayes’s “Fancy Like” became a case study in how a small, specific image can become a national chorus once listeners decide to carry it.", middle: "Its relaxed delivery and conversational details make the song feel less like a grand country statement than a family joke that happened to find a beat. The viral dance and restaurant reference were not separate from the song’s design; they were evidence of how easily the hook invited participation.", close: "The record’s story is not that the internet changed the song. It is that the song left enough room for the internet to add its own scene." },
};

const RELATED: Record<string, Array<{ rvtr: string; method: string; reason: string }>> = {
  RVTR160225: [{ rvtr: "RVTR952686", method: "contextual", reason: "Another character-first performance built around theatrical delivery." }, { rvtr: "RVTR604727", method: "contextual", reason: "A different era’s vocal drama carried by a highly distinctive lead voice." }, { rvtr: "RVTR143275", method: "contextual", reason: "A comic performance where personality turns the story into the hook." }],
};

const remaining = IDS.filter((id) => !RELATED[id]);
for (const [index, id] of remaining.entries()) {
  const candidates = IDS.filter((candidate) => candidate !== id).slice((index * 3) % (IDS.length - 3), (index * 3) % (IDS.length - 3) + 3);
  RELATED[id] = candidates.map((rvtr, offset) => ({ rvtr, method: "chart-fingerprint", reason: ["A similarly patient climb into the upper chart.", "A close rise-and-fall shape with a comparable peak week.", "Another chart run whose momentum built over several weeks."][offset] }));
}

async function main() {
  const inventory = JSON.parse(await readFile(INVENTORY, "utf8"));
  const rows = new Map<string, Row>();
  for (const row of inventory.records) if (IDS.includes(row.rvtr) && row.canonicalStatus === "resolved" && row.fileExists && row.physicalPath.startsWith("/Users/bobhopp/DJ MEDIA/VIDEO/")) rows.set(row.rvtr, row);
  if (rows.size !== IDS.length) throw new Error(`Expected 25 owned canonical rows, found ${rows.size}`);
  await mkdir(OUT, { recursive: true });
  const records = [];
  for (const rvtr of IDS) {
    const row = rows.get(rvtr)!;
    let pkg: any = null;
    try { pkg = JSON.parse(await readFile(join(PACKAGE_ROOT, `${rvtr}.json`), "utf8")); } catch { /* collector packet may not exist yet */ }
    const seed = SEEDS[rvtr];
    const facts = (pkg?.storyCards ?? []).filter((card: any) => card.rank > 0 && !card.hidden).slice(0, 2).map((card: any) => card.fact);
    const paragraphs = [seed.lede, seed.middle, facts[0] ? `${facts[0]} ${seed.close}` : seed.close];
    const preparedHero = await access(join(ROOT, "data/ops/intelligence/research-department", rvtr, "visual-assets/hero-video.jpg")).then(() => true).catch(() => false);
    records.push({ rvtr, artist: row.canonicalArtist, title: row.canonicalTitle, year: row.displayYear, yearSource: row.displayYearSource, playCount: row.playCount, chartJourney: row.chartJourneyStatus === "AVAILABLE", heroSource: preparedHero ? "prepared-video-frame" : "pending-video-frame", previousStoryStatus: row.storyStatus, headline: seed.headline, paragraphs, articleWordCount: paragraphs.join(" ").split(/\s+/).filter(Boolean).length, researchSources: [...new Set([...(seed.sources ?? []), ...(pkg?.storyCards ?? []).map((card: any) => card.sourceUrl).filter(Boolean)])], physicalPath: row.physicalPath, related: RELATED[rvtr].map((relation) => { const target = rows.get(relation.rvtr)!; return { ...relation, rvtr: target.rvtr, title: target.canonicalTitle, artist: target.canonicalArtist, ownedVideoPath: target.physicalPath, canonicalRoute: `/retroverse-2/song/${target.rvtr}` }; }) });
  }
  await writeFile(join(OUT, "preparation-manifest.json"), JSON.stringify({ version: 1, batch: "editorial-song-diversity-25", generatedAt: new Date().toISOString(), records }, null, 2) + "\n");
  await writeFile(join(ROOT, "data/ops/intelligence/editorial-diversity-25.json"), JSON.stringify({ version: 1, generatedAt: new Date().toISOString(), records }, null, 2) + "\n");
  const selection = `# Editorial Song Experience — 25-Song Diversity Proof\n\nExactly 25 canonically resolved, physically owned VIDEO songs selected across 1930s–2020s, including major/modest hits, multiple genres, varied chart shapes, and one no-Chart-Journey case.\n\n| # | RVTR | Artist | Title | Year | Playcount | Chart Journey | Story | Hero | Diversity reason |\n|---:|---|---|---|---:|---:|---|---|---|---|\n${records.map((r, i) => `| ${i + 1} | ${r.rvtr} | ${r.artist} | ${r.title} | ${r.year} | ${r.playCount ?? 0} | ${r.chartJourney ? "yes" : "no"} | ${r.previousStoryStatus} | ${r.heroSource} | ${r.chartJourney ? "trajectory proof" : "contextual/no-chart proof"} |`).join("\\n")}\n`;
  await writeFile(join(OUT, "selection-report.md"), selection);
  console.log(JSON.stringify({ selected: records.length, chartJourney: records.filter((r) => r.chartJourney).length, noChart: records.filter((r) => !r.chartJourney).length, missingHeroes: records.filter((r) => r.heroSource !== "prepared-video-frame").length }));
}
void main().catch((error) => { console.error(error); process.exitCode = 1; });
