"use client";
import { useEffect, useRef, useState } from "react";
import type { ContactRow } from "@/lib/retroverse-pass/contacts";
type Row = ContactRow & { rowKey:string; isNew?:boolean; saving?:boolean; error?:string };
const blank = { id:0, firstName:"", lastName:null, email:null, phone:null, timesSeen:0, firstSeen:null, lastSeen:null, notes:null };
const fields = ["firstName","lastName","email","phone"] as const;
export function ContactsBoard({ initialContacts, enabled }: { initialContacts:ContactRow[]; enabled:boolean }) {
 const [rows,setRows]=useState<Row[]>(initialContacts.map(c=>({...c,rowKey:`contact:${c.id}`}))); const [search,setSearch]=useState(""); const next=useRef(1); const rowsRef=useRef(rows); useEffect(()=>{rowsRef.current=rows},[rows]);
 useEffect(()=>{const t=window.setTimeout(async()=>{if(!enabled)return;const res=await fetch(`/api/bobos/contacts?q=${encodeURIComponent(search.trim())}`);const data=await res.json();if(res.ok)setRows(cur=>[...cur.filter(r=>r.isNew),...(data.contacts??[]).map((c:ContactRow)=>({...c,rowKey:`contact:${c.id}`}))])},250);return()=>window.clearTimeout(t)},[enabled,search]);
 function add(){const rowKey=`new-${next.current++}`;setRows(cur=>[{...blank,rowKey,isNew:true},...cur]);requestAnimationFrame(()=>document.querySelector<HTMLInputElement>(`[data-row-key="${rowKey}"][data-field="firstName"]`)?.focus())}
 function edit(rowKey:string,field:string,value:string){setRows(cur=>cur.map(r=>r.rowKey===rowKey?({...r,[field]:value,error:undefined}):r))}
 async function save(rowKey:string){const row=rowsRef.current.find(r=>r.rowKey===rowKey);if(!row||!row.firstName.trim())return;setRows(cur=>cur.map(r=>r.rowKey===rowKey?({...r,saving:true}):r));const res=await fetch("/api/bobos/contacts",{method:row.isNew?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...row})});const data=await res.json();if(!res.ok){setRows(cur=>cur.map(r=>r.rowKey===rowKey?({...r,saving:false,error:data.error}):r));return}setRows(cur=>cur.map(r=>r.rowKey===rowKey?({...data.contact,rowKey,isNew:false,saving:false}):r))}
 async function remove(row:Row){if(row.isNew){setRows(cur=>cur.filter(r=>r.rowKey!==row.rowKey));return}if(!window.confirm(`Delete contact ${row.firstName} ${row.lastName??""}?`))return;await fetch("/api/bobos/contacts",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id})});setRows(cur=>cur.filter(r=>r.rowKey!==row.rowKey))}
 return <section className="contacts-board"><div className="contacts-toolbar"><button className="ops-btn ops-btn--ok contacts-add" type="button" onClick={add} disabled={!enabled}>+ Add Row</button><input className="ops-input contacts-search" type="search" placeholder="Search contacts…" value={search} onChange={e=>setSearch(e.target.value)} disabled={!enabled}/></div><div className="contacts-grid-wrap"><table className="contacts-grid"><thead><tr>{["First Name","Last Name","Email","Phone","Times Seen","First Seen","Last Seen","Notes",""].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.rowKey}>{fields.map(field=><td key={field}><input className="contacts-cell" data-row-key={row.rowKey} data-field={field} value={row[field]??""} onChange={e=>edit(row.rowKey,field,e.target.value)} onBlur={()=>void save(row.rowKey)} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur()}}/></td>)}<td>{row.timesSeen}</td><td>{row.firstSeen??""}</td><td>{row.lastSeen??""}</td><td><input className="contacts-cell" data-row-key={row.rowKey} data-field="notes" value={row.notes??""} onChange={e=>edit(row.rowKey,"notes",e.target.value)} onBlur={()=>void save(row.rowKey)} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur()}}/></td><td className="contacts-actions"><button className="contacts-delete" type="button" onClick={()=>void remove(row)} aria-label={`Delete ${row.firstName}`}>×</button></td></tr>)}</tbody></table></div></section>;
}
