"use client";

import { useEffect, useRef, useState } from "react";
import type { EditorialSegment } from "@/lib/ops/media-lab/editorial/segment-manifest-client";
import { formatChapterClock } from "@/lib/ops/media-lab/chapter-time";
import { clampSourceTime, detailWindowRange, DETAIL_WINDOWS, manualClipId, temporaryClipTitle, timelinePositionForTime, type DetailWindowSeconds, type TimeRange, validClipRange } from "@/lib/ops/media-lab/manual-clip-cutter";

type Props = { year: number; jobSlug: string; sourceFilename: string; durationSeconds: number; onNotice?: (value: string) => void; onError?: (value: string) => void };
type SegmentResponse = { ok?: boolean; manifest?: { segments: EditorialSegment[]; sourceFingerprint?: string }; sourceFingerprint?: string | null; error?: string };
type Frame = { sec: number; url: string };

export function MediaLabChapterEditor(props: Props) {
  const [videoUrl, setVideoUrl] = useState(""); const [sourceFingerprint, setSourceFingerprint] = useState(""); const [clips, setClips] = useState<EditorialSegment[]>([]);
  const [playhead, setPlayhead] = useState(0); const [start, setStart] = useState<number>(); const [end, setEnd] = useState<number>(); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [windowSec, setWindowSec] = useState<DetailWindowSeconds>(60); const [detail, setDetail] = useState<TimeRange>(() => detailWindowRange(0, props.durationSeconds, 60));
  const [overviewFrames, setOverviewFrames] = useState<Frame[]>([]); const [detailFrames, setDetailFrames] = useState<Frame[]>([]); const [thumbError, setThumbError] = useState("");
  const [previewing, setPreviewing] = useState(false); const [title, setTitle] = useState(""); const [notes, setNotes] = useState("");
  const videoRef = useRef<HTMLVideoElement>(null); const endpoint = `/api/ops/media-lab/editorial/segments?year=${props.year}&jobSlug=${encodeURIComponent(props.jobSlug)}`;
  const selectedClip = clips.find((clip) => clip.id === selectedId) ?? null; const rangeValid = start != null && end != null && validClipRange(start, end, props.durationSeconds);
  const reframe = (time = playhead, size = windowSec) => setDetail(detailWindowRange(time, props.durationSeconds, size));
  function seek(sec: number) { const next = clampSourceTime(sec, props.durationSeconds); if (videoRef.current) videoRef.current.currentTime = next; setPlayhead(next); }

  useEffect(() => { reframe(0); }, [props.durationSeconds]);
  useEffect(() => { let cancelled = false; void (async () => { try { const editorial = await fetch(`/api/ops/media-lab/editorial?year=${props.year}&jobSlug=${encodeURIComponent(props.jobSlug)}`).then((r) => r.json()); if (!editorial.videoUrl) throw new Error("Source video is unavailable"); if (cancelled) return; setVideoUrl(editorial.videoUrl); const data = await fetch(endpoint).then((r) => r.json()) as SegmentResponse; if (!data.ok && data.error) throw new Error(data.error); if (cancelled) return; setClips(data.manifest?.segments ?? []); setSourceFingerprint(data.sourceFingerprint ?? data.manifest?.sourceFingerprint ?? editorial.job?.sourceFingerprint ?? ""); } catch (e) { if (!cancelled) props.onError?.(e instanceof Error ? e.message : "Could not load manual clips"); } })(); return () => { cancelled = true; }; }, [endpoint, props]);
  useEffect(() => { if (!sourceFingerprint) return; const controller = new AbortController(); const load = async (range: TimeRange, profile: "overview" | "detail", count: number, set: (frames: Frame[]) => void) => { try { const p = new URLSearchParams({ year: String(props.year), jobSlug: props.jobSlug, chapterId: `manual-${profile}`, startSec: String(range.start), endSec: String(range.end), sourceFingerprint, profile, count: String(count) }); const res = await fetch(`/api/ops/media-lab/editorial/filmstrip?${p}`, { signal: controller.signal }); const data = await res.json(); if (!res.ok) throw new Error(data.error ?? "Thumbnails unavailable"); if (!controller.signal.aborted) { set(data.frames ?? []); setThumbError(""); } } catch (e) { if (!controller.signal.aborted) setThumbError(e instanceof Error ? e.message : "Thumbnails unavailable"); } }; void load({ start: 0, end: props.durationSeconds }, "overview", 30, setOverviewFrames); void load(detail, "detail", Math.max(8, Math.ceil((detail.end - detail.start) / 5)), setDetailFrames); return () => controller.abort(); }, [detail, props.durationSeconds, props.jobSlug, props.year, sourceFingerprint]);
  function setClipSelection(clip: EditorialSegment) { setSelectedId(clip.id); setStart(clip.startSeconds); setEnd(clip.endSeconds); setTitle(clip.title); setNotes(clip.notes ?? ""); seek(clip.startSeconds); reframe(clip.startSeconds); }
  function setIn() { if (Number.isFinite(playhead) && (end == null || playhead < end)) setStart(playhead); else props.onError?.("Start must be before End."); }
  function setOut() { if (Number.isFinite(playhead) && (start == null || playhead > start)) setEnd(playhead); else props.onError?.("End must be after Start."); }
  function preview() { if (!rangeValid) return props.onError?.("Set a valid Start and End first."); setPreviewing(true); seek(start!); void videoRef.current?.play().catch(() => undefined); }
  async function persist(segment: EditorialSegment) { const res = await fetch(endpoint, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ segment }) }); const data = await res.json() as SegmentResponse; if (!res.ok || !data.ok) throw new Error(data.error ?? "Could not save clip"); setClips(data.manifest?.segments ?? []); }
  async function addClip() { if (!rangeValid || !sourceFingerprint) return props.onError?.("Set a valid range and wait for the source fingerprint."); const sequence = clips.length + 1; const now = new Date().toISOString(); const clip: EditorialSegment = { id: manualClipId(sourceFingerprint, start!, end!, sequence), sourceFilename: props.sourceFilename, sourceFingerprint, startSeconds: start!, endSeconds: end!, startTimecode: formatChapterClock(start!), endTimecode: formatChapterClock(end!), durationSeconds: end! - start!, primaryClass: "unknown", title: title.trim() || temporaryClipTitle(sequence), notes, reviewStatus: "draft", exportStatus: "not_queued", includeForExport: true, createdAt: now, modifiedAt: now }; try { await persist(clip); setSelectedId(clip.id); props.onNotice?.("Clip added to Marked Clips."); } catch (e) { props.onError?.(e instanceof Error ? e.message : "Could not add clip"); } }
  async function updateClip() { if (!selectedClip || !rangeValid) return; try { await persist({ ...selectedClip, startSeconds: start!, endSeconds: end!, startTimecode: formatChapterClock(start!), endTimecode: formatChapterClock(end!), durationSeconds: end! - start!, title: title.trim() || selectedClip.title, notes }); props.onNotice?.("Clip updated."); } catch (e) { props.onError?.(e instanceof Error ? e.message : "Could not update clip"); } }
  const summaryDuration = clips.reduce((sum, clip) => sum + (clip.includeForExport ? clip.durationSeconds : 0), 0);
  return <section className="ops-ml-manual-cutter" aria-label="Manual Clip Cutter"><header className="ops-ml-manual-cutter__header"><div><h2>Manual Clip Cutter</h2><p>{props.sourceFilename} · {formatChapterClock(props.durationSeconds)}</p></div><span className="ops-dim">Manual clips are authoritative · no AI boundaries</span></header><div className="ops-ml-manual-cutter__grid"><main><video ref={videoRef} className="ops-ml-manual-cutter__video" src={videoUrl} controls preload="metadata" onTimeUpdate={(e) => { const t = e.currentTarget.currentTime; setPlayhead(t); if (previewing && end != null && t >= end) { e.currentTarget.pause(); setPreviewing(false); } }} />
    <Timeline label="Overview Timeline" range={{ start: 0, end: props.durationSeconds }} playhead={playhead} start={start} end={end} clips={clips} frames={overviewFrames} onSeek={seek} onComplete={(time) => reframe(time)} />
    <div className="ops-ml-manual-cutter__window"><span>Detail window</span>{DETAIL_WINDOWS.map((value) => <button type="button" key={value} className={windowSec === value ? "is-active" : ""} onClick={() => { setWindowSec(value); reframe(playhead, value); }}>{value < 60 ? `${value}s` : value === 60 ? "1 min" : "5 min"}</button>)}<button type="button" onClick={() => reframe()}>Recenter</button></div>
    <Timeline label="Detail Timeline" range={detail} playhead={playhead} start={start} end={end} clips={[]} frames={detailFrames} onSeek={seek} onMarkerChange={(kind, time) => { if (kind === "start" && (end == null || time < end)) setStart(time); if (kind === "end" && (start == null || time > start)) setEnd(time); }} />
    {thumbError ? <p className="ops-ml-manual-cutter__thumb-error">Thumbnails unavailable: {thumbError}. Timelines remain usable.</p> : null}
    <div className="ops-ml-manual-cutter__controls"><button type="button" onClick={setIn}>Set Start</button><button type="button" onClick={setOut}>Set End</button><button type="button" onClick={preview} disabled={!rangeValid}>Preview Clip</button><button type="button" onClick={() => void addClip()} disabled={!rangeValid}>Add Clip</button><span>Start {start == null ? "—" : formatChapterClock(start)} · End {end == null ? "—" : formatChapterClock(end)} · Duration {rangeValid ? formatChapterClock(end! - start!) : "—"}</span></div>
    <details open className="ops-ml-manual-cutter__transcript"><summary>Transcript assistance</summary><p className="ops-dim">Select a marked clip to restore its saved range; transcription remains assistance, not boundary authority.</p></details></main><aside className="ops-ml-manual-cutter__marked"><h3>Marked Clips</h3><p className="ops-dim">{clips.length} clips · {formatChapterClock(summaryDuration)} selected duration</p>{clips.map((clip, index) => <article key={clip.id} className={selectedId === clip.id ? "is-selected" : ""}><button type="button" onClick={() => setClipSelection(clip)}><strong>{index + 1}. {clip.title}</strong><span>{clip.startTimecode} → {clip.endTimecode}</span></button><div><button type="button" onClick={preview} disabled={selectedId !== clip.id || !rangeValid}>Preview</button><button type="button" onClick={() => void updateClip()} disabled={selectedId !== clip.id || !rangeValid}>Update</button></div></article>)}</aside></div></section>;
}

function Timeline(props: { label: string; range: TimeRange; playhead: number; start?: number; end?: number; clips: EditorialSegment[]; frames: Frame[]; onSeek: (time: number) => void; onComplete?: (time: number) => void; onMarkerChange?: (kind: "start" | "end", time: number) => void }) {
  const track = useRef<HTMLDivElement>(null); const dragging = useRef(false); const markerDrag = useRef<"start" | "end" | null>(null); const lastSeek = useRef(0); const pct = (sec: number) => `${timelinePositionForTime(sec, props.range) * 100}%`;
  const seekEvent = (event: React.PointerEvent<HTMLDivElement>, complete = false) => { const rect = track.current?.getBoundingClientRect(); if (!rect) return; const time = props.range.start + Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)) * (props.range.end - props.range.start); const now = performance.now(); if (complete || now - lastSeek.current > 40) { props.onSeek(time); lastSeek.current = now; } if (complete) props.onComplete?.(time); };
  const marker = (time: number | undefined, kind: "start" | "end") => time != null && time >= props.range.start && time <= props.range.end ? <button type="button" className={`ops-ml-manual-timeline__marker is-${kind}`} style={{ left: pct(time) }} onPointerDown={(e) => { e.stopPropagation(); markerDrag.current = kind; e.currentTarget.parentElement?.setPointerCapture(e.pointerId); }}>{kind === "start" ? "IN" : "OUT"}</button> : null;
  return <section className="ops-ml-manual-timeline"><header><strong>{props.label}</strong><span>{formatChapterClock(props.range.start)} → {formatChapterClock(props.range.end)} · {formatChapterClock(props.playhead)}</span></header><div ref={track} className="ops-ml-manual-timeline__track" onPointerDown={(e) => { dragging.current = true; e.currentTarget.setPointerCapture(e.pointerId); seekEvent(e); }} onPointerMove={(e) => { if (markerDrag.current) { const rect = track.current?.getBoundingClientRect(); if (rect) props.onMarkerChange?.(markerDrag.current, props.range.start + Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width)) * (props.range.end - props.range.start)); } else if (dragging.current) seekEvent(e); }} onPointerUp={(e) => { if (markerDrag.current) markerDrag.current = null; else if (dragging.current) seekEvent(e, true); dragging.current = false; }} onPointerCancel={() => { dragging.current = false; markerDrag.current = null; }}>
    <div className="ops-ml-manual-timeline__frames">{props.frames.length ? props.frames.map((frame) => <img key={frame.sec} src={frame.url} alt="" draggable={false} />) : <span className="ops-ml-manual-timeline__placeholder">Loading filmstrip…</span>}</div>{props.clips.map((clip) => <span key={clip.id} className="ops-ml-manual-timeline__clip" style={{ left: pct(clip.startSeconds), width: `${Math.max(0, timelinePositionForTime(clip.endSeconds, props.range) - timelinePositionForTime(clip.startSeconds, props.range)) * 100}%` }} />)}{props.start != null && props.end != null ? <span className="ops-ml-manual-timeline__selection" style={{ left: pct(Math.max(props.start, props.range.start)), width: `${Math.max(0, timelinePositionForTime(Math.min(props.end, props.range.end), props.range) - timelinePositionForTime(Math.max(props.start, props.range.start), props.range)) * 100}%` }} /> : null}{marker(props.start, "start")}{marker(props.end, "end")}<span className="ops-ml-manual-timeline__playhead" style={{ left: pct(props.playhead) }}><i /></span></div></section>;
}
