"use client";

import { useEffect, useMemo, useState } from "react";
import type { EditorialChapterRow } from "@/lib/ops/media-lab/editorial/editorial-types";
import { formatChapterClock } from "@/lib/ops/media-lab/chapter-time";
import { DOCUMENTARY_SCENE_CLASSES, PERFORMANCE_CLASSES, PRIMARY_SEGMENT_CLASSES, REVIEW_STATUSES, type EditorialSegment } from "@/lib/ops/media-lab/editorial/segment-manifest-client";

type Props = { year: number; jobSlug: string; sourceFilename: string; sourceDurationSeconds: number; chapter: EditorialChapterRow; playheadSeconds: number; onSetIn: () => void; onSetOut: () => void; onSelectBounds: (start: number, end: number) => void; onNotice?: (message: string) => void; onError?: (message: string) => void };

function idFor(jobSlug: string, start: number, end: number) { return `SEG-${jobSlug.slice(0, 12).toUpperCase()}-${Math.round(start * 1000).toString(36).toUpperCase()}-${Math.round(end * 1000).toString(36).toUpperCase()}`; }
function blank(chapter: EditorialChapterRow, jobSlug: string, sourceFingerprint = ""): EditorialSegment { const now = new Date().toISOString(); return { id: idFor(jobSlug, chapter.startSec, chapter.endSec), sourceFilename: "", sourceFingerprint, startSeconds: chapter.startSec, endSeconds: chapter.endSec, startTimecode: chapter.start, endTimecode: chapter.end, durationSeconds: chapter.durationSec, primaryClass: "unknown", title: chapter.title, reviewStatus: "draft", exportStatus: "not_queued", includeForExport: false, createdAt: now, modifiedAt: now }; }

export function WoodstockSegmentPanel(props: Props) {
  const [segments, setSegments] = useState<EditorialSegment[]>([]);
  const [sourceChanged, setSourceChanged] = useState(false);
  const [sourceFingerprint, setSourceFingerprint] = useState("");
  const [draft, setDraft] = useState<EditorialSegment>(() => blank(props.chapter, props.jobSlug));
  const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false);
  const [filter, setFilter] = useState("all");
  const endpoint = `/api/ops/media-lab/editorial/segments?year=${props.year}&jobSlug=${encodeURIComponent(props.jobSlug)}`;

  async function load() { const res = await fetch(endpoint); const data = await res.json() as { ok?: boolean; manifest?: { segments: EditorialSegment[]; sourceFingerprint?: string }; sourceChanged?: boolean; sourceFingerprint?: string | null; error?: string }; if (!res.ok || !data.ok) throw new Error(data.error ?? "Could not load segments"); setSegments(data.manifest?.segments ?? []); setSourceChanged(Boolean(data.sourceChanged)); setSourceFingerprint(data.sourceFingerprint ?? data.manifest?.sourceFingerprint ?? ""); }
  useEffect(() => { void load().catch((e) => props.onError?.(e instanceof Error ? e.message : "Could not load segments")); }, [endpoint]);
  useEffect(() => { const existing = segments.find((segment) => segment.id === draft.id); if (!existing && !dirty) setDraft(blank(props.chapter, props.jobSlug, sourceFingerprint)); }, [props.chapter.id, segments, sourceFingerprint]);
  const visible = useMemo(() => segments.filter((s) => filter === "all" || s.primaryClass === filter).sort((a, b) => a.startSeconds - b.startSeconds), [segments, filter]);
  function patch(patch: Partial<EditorialSegment>) { setDraft((current) => ({ ...current, ...patch, modifiedAt: new Date().toISOString() })); setDirty(true); }
  function patchBounds(startSeconds: number, endSeconds: number) { patch({ startSeconds, endSeconds, startTimecode: formatChapterClock(startSeconds), endTimecode: formatChapterClock(endSeconds), durationSeconds: Math.round((endSeconds - startSeconds) * 100) / 100 }); }
  async function save(next = false) { setBusy(true); try { const segment = { ...draft, sourceFilename: props.sourceFilename, startTimecode: formatChapterClock(draft.startSeconds), endTimecode: formatChapterClock(draft.endSeconds), durationSeconds: Math.round((draft.endSeconds - draft.startSeconds) * 100) / 100 }; const res = await fetch(endpoint, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ segment, acknowledgeSourceChange: sourceChanged }) }); const data = await res.json() as { ok?: boolean; manifest?: { segments: EditorialSegment[] }; error?: string }; if (!res.ok || !data.ok) throw new Error(data.error ?? "Could not save segment"); setSegments(data.manifest?.segments ?? []); setDirty(false); props.onNotice?.("Segment saved."); if (next) props.onSelectBounds(draft.endSeconds, Math.min(props.sourceDurationSeconds, draft.endSeconds + 1)); } catch (e) { props.onError?.(e instanceof Error ? e.message : "Could not save segment"); } finally { setBusy(false); } }
  async function toggleInclude(segment: EditorialSegment) { setBusy(true); try { const res = await fetch(endpoint, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ segment: { ...segment, includeForExport: !segment.includeForExport }, acknowledgeSourceChange: sourceChanged }) }); const data = await res.json() as { ok?: boolean; manifest?: { segments: EditorialSegment[] }; error?: string }; if (!res.ok || !data.ok) throw new Error(data.error ?? "Could not update export selection"); setSegments(data.manifest?.segments ?? []); } catch (e) { props.onError?.(e instanceof Error ? e.message : "Could not update export selection"); } finally { setBusy(false); } }
  async function remove() { if (!window.confirm(`Delete ${draft.title || "this segment"} (${draft.id})?\n${draft.startTimecode} → ${draft.endTimecode}`)) return; setBusy(true); try { const res = await fetch(endpoint, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ deleteId: draft.id }) }); const data = await res.json() as { ok?: boolean; manifest?: { segments: EditorialSegment[] }; error?: string }; if (!res.ok || !data.ok) throw new Error(data.error ?? "Could not delete segment"); setSegments(data.manifest?.segments ?? []); setDraft(blank(props.chapter, props.jobSlug)); setDirty(false); } catch (e) { props.onError?.(e instanceof Error ? e.message : "Could not delete segment"); } finally { setBusy(false); } }
  function duplicate() { const now = new Date().toISOString(); setDraft({ ...draft, id: `${draft.id}-COPY-${Math.random().toString(36).slice(2, 7).toUpperCase()}`, title: `${draft.title} copy`, createdAt: now, modifiedAt: now, reviewStatus: "draft", exportStatus: "not_queued" }); setDirty(true); }

  return <section className="ops-ml-woodstock-panel" aria-label="Documentary segment editor">
    {sourceChanged ? <div className="ops-ml-woodstock-warning">Source fingerprint changed. Saved work is retained; acknowledge deliberately on the next save.</div> : null}
    <div className="ops-ml-woodstock-actions"><button type="button" onClick={() => patchBounds(props.playheadSeconds, draft.endSeconds)}>Set In</button><button type="button" onClick={() => patchBounds(draft.startSeconds, props.playheadSeconds)}>Set Out</button><button type="button" onClick={() => props.onSelectBounds(draft.startSeconds, draft.endSeconds)}>Preview Selection</button><button type="button" onClick={() => { setDraft(blank(props.chapter, props.jobSlug)); setDirty(true); }}>New Segment</button></div>
    <p className="ops-dim">{draft.id} · {draft.startTimecode} → {draft.endTimecode} · {draft.durationSeconds.toFixed(2)}s {dirty ? "· UNSAVED" : ""}</p>
    <div className="ops-ml-woodstock-grid">
      <label>Primary class<select value={draft.primaryClass} onChange={(e) => patch({ primaryClass: e.target.value as EditorialSegment["primaryClass"] })}>{PRIMARY_SEGMENT_CLASSES.map((value) => <option key={value}>{value}</option>)}</select></label>
      {draft.primaryClass === "performance" ? <><label>Performance subtype<select value={draft.secondaryClass ?? ""} onChange={(e) => patch({ secondaryClass: e.target.value || undefined })}><option value="">Choose…</option>{PERFORMANCE_CLASSES.map((value) => <option key={value}>{value}</option>)}</select></label><label>Song<input value={draft.song ?? ""} onChange={(e) => patch({ song: e.target.value })} /></label><label>Artist / people<input value={draft.artistPeople ?? ""} onChange={(e) => patch({ artistPeople: e.target.value })} /></label></> : null}
      {draft.primaryClass === "documentary_scene" ? <label>Documentary subtype<select value={draft.secondaryClass ?? ""} onChange={(e) => patch({ secondaryClass: e.target.value || undefined })}><option value="">Choose…</option>{DOCUMENTARY_SCENE_CLASSES.map((value) => <option key={value}>{value}</option>)}</select></label> : null}
      <label>Title<input value={draft.title} onChange={(e) => patch({ title: e.target.value })} /></label><label>Festival day<input value={draft.festivalDay ?? ""} onChange={(e) => patch({ festivalDay: e.target.value })} /></label><label>Approximate time<input value={draft.approximateFestivalTime ?? ""} onChange={(e) => patch({ approximateFestivalTime: e.target.value })} /></label><label>Description<textarea value={draft.description ?? ""} onChange={(e) => patch({ description: e.target.value })} /></label><label>Notes<textarea value={draft.notes ?? ""} onChange={(e) => patch({ notes: e.target.value })} /></label><label>Review status<select value={draft.reviewStatus} onChange={(e) => patch({ reviewStatus: e.target.value as EditorialSegment["reviewStatus"] })}>{REVIEW_STATUSES.map((value) => <option key={value}>{value}</option>)}</select></label>
    </div>
    <div className="ops-ml-woodstock-actions"><button type="button" disabled={busy} onClick={() => void save(false)}>Mark Clip</button><button type="button" disabled={busy} onClick={() => void save(true)}>Mark &amp; Next</button><button type="button" onClick={duplicate}>Duplicate</button><button type="button" onClick={() => patch({ reviewStatus: draft.reviewStatus === "rejected" ? "draft" : "rejected" })}>{draft.reviewStatus === "rejected" ? "Restore" : "Reject"}</button><button type="button" disabled={busy} onClick={() => void remove()}>Delete</button></div>
    <div className="ops-ml-woodstock-list"><h3>Marked Clips</h3><p className="ops-dim">{visible.length} marked · {visible.filter((s) => s.includeForExport).length} selected for export</p><label>Filter <select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All</option>{PRIMARY_SEGMENT_CLASSES.map((value) => <option key={value}>{value}</option>)}</select></label>{visible.map((segment) => <div key={segment.id}><button type="button" onClick={() => { setDraft(segment); setDirty(false); props.onSelectBounds(segment.startSeconds, segment.endSeconds); }}><span>{segment.startTimecode} → {segment.endTimecode} · {segment.primaryClass}</span><strong>{segment.title || "Untitled"}</strong><small>{segment.reviewStatus} · {segment.includeForExport ? "Include for Export" : "Exclude from Export"}</small></button><button type="button" disabled={busy} onClick={() => void toggleInclude(segment)}>{segment.includeForExport ? "Exclude from Export" : "Include for Export"}</button></div>)}</div>
  </section>;
}
