"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { RV_CATEGORY_BY_ID, RV_CATEGORIES, RV_REGISTRY } from "@/lib/bobos/rv-registry";
import { formatRvId } from "@/lib/bobos/rv-ids";
import "./rv-directory.css";

export default function RvDirectoryPage() {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [status, setStatus] = useState("all"); const [workspace, setWorkspace] = useState("all"); const [sort, setSort] = useState("id");
  const entries = useMemo(() => RV_REGISTRY.filter((entry) => { const text = `${entry.id} ${entry.title} ${entry.description} ${entry.route ?? ""}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (category === "all" || entry.category === category) && (status === "all" || entry.status === status) && (workspace === "all" || entry.workspace === workspace); }).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "status" ? a.status.localeCompare(b.status) : a.id.localeCompare(b.id)), [query, category, status, workspace, sort]);
  return <main className="rv-directory"><header><p className="rv-directory__eyebrow">BobOS architecture · master reference</p><h1>RV Directory</h1><p>Every registered BobOS page, workspace, dashboard, tool, and panel in one inventory.</p></header><div className="rv-directory__filters"><input placeholder="Search ID, title, route, or description…" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All categories</option>{RV_CATEGORIES.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.title}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option>{["Active", "Experimental", "Hidden", "Deprecated", "Retired"].map((item) => <option key={item}>{item}</option>)}</select><select value={workspace} onChange={(e) => setWorkspace(e.target.value)}><option value="all">All workspaces</option>{[...new Set(RV_REGISTRY.map((item) => item.workspace))].map((item) => <option key={item}>{item}</option>)}</select><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="id">Sort: RV ID</option><option value="title">Sort: title</option><option value="status">Sort: status</option></select></div><p className="rv-directory__count">Showing {entries.length} of {RV_REGISTRY.length} registry entries</p><div className="rv-directory__table-wrap"><table><thead><tr><th>RV ID</th><th>Title</th><th>Category</th><th>Workspace</th><th>Route</th><th>Status</th><th>Panel</th><th>Cockpit</th><th>Description</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td><span className="rv-directory__id" style={{ borderColor: RV_CATEGORY_BY_ID[entry.category].accent }}>{formatRvId(entry.id)}</span></td><td>{entry.route ? <Link href={entry.route}>{entry.title}</Link> : entry.title}</td><td>{entry.category} · {RV_CATEGORY_BY_ID[entry.category].title}</td><td>{entry.workspace}</td><td><code>{entry.route ?? "—"}</code></td><td><span className={`rv-directory__status rv-directory__status--${entry.status.toLowerCase()}`}>{entry.status}</span></td><td>{entry.panelEligible ? "Yes" : "No"}</td><td>{entry.cockpitEligible ? "Yes" : "No"}</td><td>{entry.description}</td></tr>)}</tbody></table></div></main>;
}
